# Outline {#outline}

This outline describes the questions that the intermediate course will answer.
It assumes learners have completed the novice course, 
which means they know how to write code (in Python or R) that reads, analyses and plots a dataset.

## The Unix Shell

http://swcarpentry.github.io/shell-novice/
https://merely-useful.github.io/still-magic/en/shell.html

-   How do I navigate my filesystem?
    -   moving about (cd, ls, ., ..)
    -   files and directories (ls, cp, mkdir, mv, rm)
    -   paths (absolute, relative, special) 
-   How do I examine and/or edit a text file?
    -   difference between text and binary files
    -   running a text editor
    -   operating on text (cat, wc, head, tail, etc)
    -   finding things (find, grep)
-   How do I combine multiple commands?
    -   pipes and filters
    -   loops
-   Variables
-   Shell scripts
-   Shortcuts
    -   tab completion
    -   previous commands (up arrow, control-r)
    -   history
-   Getting help
    -   --help, man

## Automating analyses

http://swcarpentry.github.io/make-novice/
https://merely-useful.github.io/still-magic/en/automate.html

-   How do I write a simple Makefile? 
-   How can I abbreviate the rules in my Makefiles? 
-   How can I write a Makefile to update things when my scripts have changed rather than my input files?
-   How can I define rules to operate on similar files? 
    -   Pattern rules
-   How can I eliminate redundancy in my Makefiles?
    -   Variables
    -   Functions
-   How should I document a Makefile?

## Configuring software

https://merely-useful.github.io/still-magic/en/configure.html

-   How do I parse the command line from within a Python script?
    -   basic structure of python scripts
    -   argparse
-   How would I implement a configuration file?

## GitHub

-   How do I manage multiple development branches?
-   How do I suggest changes to other people's code?
    -   Forking
    -   Pull requests

## Testing

http://swcarpentry.github.io/python-novice-inflammation/08-defensive/index.html
http://katyhuff.github.io/python-testing/
https://merely-useful.github.io/still-magic/en/unit.html

-   Why should I test my code?
-   How do I implement tests/checks at specific points within my code?
    -   Assertions
    -   Exceptions
-   How do I test the overall behaviour of parts of my code?
    -   Unit testing
-   How can I run commands automatically every time a repository is updated?
    -   Continuous integration
    -   Travis

## Packaging

https://carpentrieslab.github.io/python-aos-lesson/01-conda/index.html
https://merely-useful.github.io/still-magic/en/package.html

-   How do I install and manage my Python environment?
    -   Python distributions (Anaconda)
    -   Package managers (pip, conda)
    -   conda environments
-   How can I write a package that can be installed via pip?
