# Getting Started with Python

As stated in the intro, our overall goal is to work with people, programs 
and data. In this section, we will focus on programs and data as we learn 
how to run Python code and  
how data is stored and accessed on a computer. 

## Introduction to Spyder

Starting with programs - over the entirety of this book, we'll be writing 
programs (or, in verb form, *programming*) in order to accomplish our goals 
of working with data on the computer. 
Programming is one way to make a computer do something for us. 
Instead of clicking, we'll mostly be typing; instead of doing 
what someone else has pre-defined, we'll have a lot of flexibility to 
do what we want. 

Just like using a web browser to access websites, and a program like 
Word to write documents, it's helpful to have a program on your computer 
that is designed to make it easy to write and run code. This kind of program 
is called an "IDE" or Integrated Development Environment. 

The one we'll be using in this book for writing Python code is called Spyder.
Spyder (like many IDEs) opens up and has many panes, that each have a different 
purpose. 

TODO: Screenshot or schematic.

We'll take it slowly and introduce the purpose of each pane one-by-one. 
To start with, we'll focus on the left and lower-right panes, as that's 
where the bulk of our coding will happen. 

## Running Code in the Console

Now that we have our code-writing-and-running environment open, it's time to 
actually run some code. 

In the bottom right pane, you can see something called the "console". This 
is a program that is constantly ready and waiting to take in code and run it; as 
a Python console, the language it expects to see is Python. Here's 
an example you can type or copy in: 

```{python}
  print("It was the best of times, it was the worst of times.")
```

As you might guess from the name, the Python `print()` function 
takes in text (indicated by the quotes) and then prints the text back out to the console. 
Python has many built-in functions, that allow you to do different things: 

```{python}
len("Sydney Carton")
sorted(["Samuel", "Nathaniel", "Augustus", "Tracy"]
min([4, 2/3, -3, 6.25])
pow(5,3)
```

Part of learning to program is learning some of the core Python functions and 
what they do; in upcoming chapters, we'll focus on functions that allow you to 
read in and maniuplate data. At some point it may be helpful to write your 
*own* functions, which we'll also cover in another chapter. 

## Running Code via Scripts

Can you imagine a sitution where continuing to type code into the console 
could become tedious or challenging? 

Here are some examples: 

* Wanting to run the same piece of code many times (you 
*can* use the up-arrow to see previous commands - try it! - but if you 
run many commands, your history will quickly become more cluttered. 
* Needing to re-run a piece of code
* Most important - when you close Spyder, everything you've typed into the 
console is gone. If you want to start again, you'll need to re-enter everything. 

So we're motivated to find a way to write and run code where we're keeping 
a record as we go along, and it is easy to run code again, in chunks. 

The answer to these challenges is to move to the left pane of the Spyder 
IDE. This is a script - a text file with Python code. Try copying in some 
of the commands we've already run: 

```{python}
TBD
```

TODO: Screenshot or animated gif. 

Now these commands are written in the script, but nothing has happened yet. 
In order to run the commands from the script (just like we did in the console), 
we'll have to use various run commands. You can see these under the "Run" menu; 
but typically you'll want to learn at least one or two keyboard shortcuts so 
it becomes quick and easy to run code that's written in a script. Try "running" 
the lines in your script. You should see their output in the console on the 
bottom right. 

Sometimes, when you want to experiment or check something, it can make sense 
to write and run Python code in the console. However, most of the time, you'll 
want to write and run your code from a script.  Using 
scripts has the benefit of saving your work, while also being able to run 
the code just like in the console. The script then has the added benefit of 
being easy to share and runnable outside of the IDE. 

We have now told the computer what to do by using Python code, and we have run that 
code in two different ways within our "workbench" - the Spyder IDE. Let's 
see what else we can use in this environment to help us. 

## Variables

Besides running functions that *do* something (as above), we'll also want 
to use Python to keep track of information that we're using throughout 
our analysis. We save that information by giving it a name (called a 
[variable](glossary.html#variable-python)), 
using the name, an equals sign (`=`) and then the information to save. 
For example: 

```{python}
message = "It is a far, far better thing that I do, than I have ever done"
name_length = len("Sydney Carton")
```

These variables can then be used later in functions like `print()`: 

```{python}
print("My message:", message)
print("Letters in name:", name_length)
```

On the top right pane, there's a 
tab that says "Variable Explorer". If you click on that, you'll see the 
variables you just created, with some additional information about the *Type* 
of information - `str` (string), `int` (integer), `float` (a "floating point" 
number, or decimal) and more. 

## Getting Help

That top-right pane can also give us additional information; one of 
the other tabs says "Help". The main way to look up a a particular function 
or type is to type it into the Console and then type the Help shortcut (which 
is `CTRL-I`). So, if you wanted to look up information about the `len()` 
function, we used above, you can type the following into the console and 
then use the help shortcut: 

```{python}
len
```

Typing the full name of the function (without pressing enter) 
with the Help tab selected will also 
trigger the help page about that function: 

```{python}
len()
```

Sometimes, however, your questions won't fit well within the built-in help pages, 
available through Spyder. This often happens when you need to do something 
completely new and you don't know where to start. In that scenario, there are 
multiple internet resources that are helpful:

* blogs
* question pages on Stack Overflow
* Twitter

Sometimes these resources can be overwhelming and confusing. Some things to 
look for on a Stack Overflow answer: 

* Is the question clearly stated and is there example code? If you're 
debugging, does the example code look like yours? 
* Answers have upvotes and downvotes. Is there one clear answer that has a lot 
of upvotes in response to a question? 
* How complex is the answer? While some questions will necessarily have a 
complicated answer, for many common programming tasks, there should be a 
few-line solution to the question. 
* Do you recognize any terms in the solution? If you don't, are there other 
terms that you could search on? 

## Data on a Computer

In the beginning of this chapter, we talked about learning to work with 
*programs* and *data*. We've now covered many aspects of our new 
programming environment, so this chapter will conclude with a short discussion 
of data. 

Data is simply information that's been stored in some permanent form. One 
could think of family photos and old credit card statements as data about a 
family over time. In the context of data analysis via programming, we're 
mostly going to be concerned with text-based data that has been saved as 
a file on your computer. 

When you have a data file on your computer, it's actually saved on your 
computer's hard drive or [disk](glossary.html#disk). This is a componenent of the computer that
is used for long-term storage of information - not just data files, but all 
of the programs you use on computer are also stored on disk. 

When we read a file using Python, we're making a copy of the information 
contained in the file on disk in the computer's 
[memory](glossary.html#memory). Memory is a temporary 
storage location for information, and it is used by programs for speed. 
However, if you use a program like Python to manipulate the copy of data that 
has been loaded into memory, those changes will be lost when the program 
quits and that memory space is cleared. Persistent changes need to be saved 
back to new or updated files on disk. 

## Data Location

Anything saved on disk is placed somewhere in the computer's 
[filesystem](glossary.html#filesystem) - 
a hierarchy of folders, which in programming-speak, are called 
[directories](glossary.html#directory). 
Because directories are nested, they are sometimes drawn as branching 
diagrams - another name for a filesystem is [directory tree](glossary.html#directory-tree). 

The interface we use to interact with our computer usually provides a 
shortcuts to commonly-used directories in the file system - Documents, Pictures, 
Downloads, the Desktop. These directories are usually nested into a "Home" 
directory which is associated with your account on the computer. If you open 
up your computer's file browser, the folder it opens is usually your "Home" 
directory. 

In order to interact with data via Python, we need to be able to describe that 
data file's location in the file system. Because it's not efficient to use 
pictures of nested directories or click through several folders to describe 
where a file is, the shorthand way to describe a series of nested directories 
in nearly all programming languages 
is with a slash (`/`) between folders that are nested inside each other. 
This list of directories is called a *path*. 

So to provide the file system location of a data file - either to read as input 
or save information as output - we need a path to that location. We then have 
two ways to write that path, depending on where the path begins. 

*Absolute Paths*

An absolute path describes how to get to a particular directory from the very 
top of your computer's file system (which, paradoxically, is also called the 
"root" of the file system, because every other directory branches off from it). 
To indicate that the path is starting from the top of the file system, the 
first character of the path is a slash (`/`), followed by the path of 
directories that leads to the desired file. So if I had a spreadsheet stored 
in the `2019-data` folder of my `finances` folder in my Documents folder 
(which is inside my home folder)
the absolute path would look something like: 

```{python}
abs_path = "/home/josefina/Documents/finances/2019-data/"
```

*Relative Paths*

The other way to describe a path is *relative* to a certain starting point 
in the file system. The reason this works is that most programming languages 
(including Python) assume that you are running commands from a particular 
location in the file system, called the *working directory*. It can be quicker 
to provide a path that is relative to this working directory location than 
to type out an absolute path. 

You can see which
 location your computer is using by typing this command (which stand for 
"print working directory") into the Python console: 

```{python}
pwd()
```

Instead of starting with a slash, relative paths can begin with one of three 
options: 

* a dot (`.`) - this is a shortcut for the current working directory
* a double-dot (`..`) - this is a shortcut for indicating the directory 
above the current working directory. 
* the name of a sub-directory in the current working directory

So to reference a data sub-directory, in a project folder contained in 
my current working directory, the following are equivalent: 

```{python}
'./project/data'
'project/data'
```

Usually our Desktop and Downloads directories are both sub-directories of 
Home. If my current working directory was my Desktop, but I wanted to acces 
something in my Downloads folder, I would first need to move into the 
directory "above" my current directory (which would be Home) and then into 
the Downloads sub-directory. In path notation, that looks like this: 

```{python}
pwd()
    '/home/raoul/Desktop'
print('../Downloads')
```

## Exercises

1. Run each of the functions above. Can you explain what each function 
expects as input, and what kind of output it produces? 

1. What would be the pros and cons of using the console versus a script in each situation? 
- Writing a data analysis with multiple steps. 
- Opening a new data set and exploring its dimensions. 
- Checking the value of a variable. 

1. You've saved a string of interesting data to a variable. 
```{python}
sentence = "One fish, two fish, red fish, blue fish."
```
How can you count the occurrences of the letter "f"?

1. After googling "how to read csv file python", these two answers pop up: 
  https://stackoverflow.com/questions/41585078/how-do-i-read-and-write-csv-files-with-python/41585079
  https://stackoverflow.com/questions/5788521/reading-a-csv-file-using-python
- What is useful about each page? 
- Do you understand all of the code in the second page? 
- There are many options given in the first Stack Overflow page. Which one seems like a good place to start? 
- Both pages include python libraries (extra tools), which are added to the 
code using `import`. Based on this information, looking at the options shown 
in these two pages, what are two libraries that can be used to 
read in csv files? 

1. Try reading a csv file: 
```{python}
import pandas
data = pandas.read_csv("TBD.csv")
```
Which pane in Spyder will show our new `data` object? What happens when you click on it? 

1. Screenshot + file browser // Why will `read_csv("mutant_data.csv") fail? 

1. Image --> folders
Amanda is currently working on her squid study project, with her "working
directory" inside the `squid` folder. She wants to read in a data file from 
the `data` folder inside the `reference` folder. 
- What is her current working directory (as a path)?
- Describe the path that will allow her to access the data, first as a 
relative path, then as an absolute path. 

1. Memory vs disk. 
```{python}
# read data
# add values
# print the top 10 lines

```
Why is the new table gone when you re-open the spreadsheet on your computer? 
What action would allow you to keep the information from the new table for the future? 

