# Getting Started with Python

## Getting started

-   What are the different ways I can interact with software?
    -   console
    -   scripts
-   How can I find and view help?
    -   In the IDE
    -   Stack Overflow
-   How can I inspect data while I'm working on it?
    -   table viewers
-   Where does stuff actually live on my computer?
    -   directory structure on Windows and Unix
    -   absolute vs. relative paths
    -   data on disk vs. data in memory
    
## Learning Objectives

- Compare and contrast the benefits of running code in the console versus a script. 
- Answer a question about a function by looking it up in Spyder. 
- Distinguish between a helpful and less helpful Stack Overflow answer. 
- Identify which Spyder pane will show you a window of a loaded  table. 
- Troubleshoot an error that arises because of a working directory / path issue
- Given a directory structure and two file locations, describe how to 
access the target location via an absolute or relative path. 
 
## Exercises

1. What would be the pros and cons of using the console versus a script in each situation? 
- Writing a data analysis with multiple steps. 
- Opening a new data set and exploring its dimensions. 
- Checking the value of a variable. 

2. You've saved a string of interesting data to a variable. 
```{python}
sentence = "Lift as you rise."
```
How can you find a string method that allows you to count the occurrences of the letter "l."
Follow up: find lower (vs upper)

3. After googling "how to read csv file python", these two answers pop up: 
  https://stackoverflow.com/questions/41585078/how-do-i-read-and-write-csv-files-with-python/41585079
  https://stackoverflow.com/questions/5788521/reading-a-csv-file-using-python
What are two libraries you could use?
Which option listed in the first example seems like the best one? 

4. Load data, look for variable browser

5. Screenshot + file browser // Why will `read_csv("mutant_data.csv") fail? 

6. Image --> folders
Amanda is currently working on her squid study project, which is located in the 
folder path /home/amanda/squid. If she wants to read a file from the 
octopus study that she's working on (in /home/amanda/octopus/data).  
- What is her current working directory (as a path)?
- Describe the path that will allow her to access the data, first as a 
relative path, then as an absolute path. 

7. Memory vs disk. 
```{python}
# read data
# add values
# print the top 10 lines

```
Why is the new table gone when you re-open the spreadsheet? What action would 
allow you to keep the information from the new table for the future? 

