# Reproducibility

```{r py-reproducibility-setup, include=FALSE}
source("_common.R")
```

## Data on a Computer

In the beginning of this chapter, we talked about learning to work with 
*programs* and *data*. We've now covered many aspects of our new 
programming environment, so this chapter will conclude with a short discussion 
of data. 

Data is simply information that's been stored in some permanent form. One 
could think of family photos and old credit card statements as data about a 
family over time. In the context of data analysis via programming, we're 
mostly going to be concerned with text-based data that has been saved as 
a file on your computer. 

When you have a data file on your computer, it's actually saved on your 
computer's hard drive or [disk](glossary.html#disk). This is a componenent of the computer that
is used for long-term storage of information - not just data files, but all 
of the programs you use on computer are also stored on disk. 

When we read a file using Python, we're making a copy of the information 
contained in the file on disk in the computer's 
[memory](glossary.html#memory). Memory is a temporary 
storage location for information, and it is used by programs for speed. 
However, if you use a program like Python to manipulate the copy of data that 
has been loaded into memory, those changes will be lost when the program 
quits and that memory space is cleared. Persistent changes need to be saved 
back to new or updated files on disk. 

## Data Location

Anything saved on disk is placed somewhere in the computer's 
[filesystem](glossary.html#filesystem) - 
a hierarchy of folders, which in programming-speak, are called 
[directories](glossary.html#directory). 
Because directories are nested, they are sometimes drawn as branching 
diagrams - another name for a filesystem is [directory tree](glossary.html#directory-tree). 

The interface we use to interact with our computer usually provides a 
shortcuts to commonly-used directories in the filesystem - Documents, Pictures, 
Downloads, the Desktop. These directories are usually nested into a "Home" 
directory which is associated with your account on the computer. If you open 
up your computer's file browser, the folder it opens is usually your "Home" 
directory. 

In order to interact with data via Python, we need to be able to describe that 
data file's location in the filesystem. Because it's not efficient to use 
pictures of nested directories or click through several folders to describe 
where a file is, the shorthand way to describe a series of nested directories 
in nearly all programming languages 
is with a slash (`/`) between folders that are nested inside each other. 
This list of directories is called a *path*. 

So to provide the filesystem location of a data file - either to read as input 
or save information as output - we need a path to that location. We then have 
two ways to write that path, depending on where the path begins. 

*Absolute Paths*

An absolute path describes how to get to a particular directory from the very 
top of your computer's filesystem (which, paradoxically, is also called the 
"root" of the filesystem, because every other directory branches off from it). 
To indicate that the path is starting from the top of the filesystem, the 
first character of the path is a slash (`/`), followed by the path of 
directories that leads to the desired file. So if I had a spreadsheet stored 
in the `2019-data` folder of my `finances` folder in my Documents folder 
(which is inside my home folder)
the absolute path would look something like: 

```{python}
abs_path = "/home/josefina/Documents/finances/2019-data/"
```

*Relative Paths*

The other way to describe a path is *relative* to a certain starting point 
in the filesystem. The reason this works is that most programming languages 
(including Python) assume that you are running commands from a particular 
location in the filesystem, called the *working directory*. It can be quicker 
to provide a path that is relative to this working directory location than 
to type out an absolute path. 

You can see which
 location your computer is using by typing this command (which stand for 
"print working directory") into the Python console: 

```{python eval=FALSE}
pwd()
```

Instead of starting with a slash, relative paths can begin with one of three 
options: 

* a dot (`.`) - this is a shortcut for the current working directory
* a double-dot (`..`) - this is a shortcut for indicating the directory 
above the current working directory. 
* the name of a sub-directory in the current working directory

So to reference a data sub-directory, in a project folder contained in 
my current working directory, the following are equivalent: 

```{python eval=FALSE}
'./project/data'
'project/data'
```

Usually our Desktop and Downloads directories are both sub-directories of 
Home. If my current working directory was my Desktop, but I wanted to acces 
something in my Downloads folder, I would first need to move into the 
directory "above" my current directory (which would be Home) and then into 
the Downloads sub-directory. In path notation, that looks like this: 

```{python eval=FALSE}
pwd()
    '/home/raoul/Desktop'
print('../Downloads')
```

## Exercises

1. Screenshot + file browser // Why will `read_csv("mutant_data.csv") fail? 

1. Image --> folders
Amanda is currently working on her squid study project, with her "working
directory" inside the `squid` folder. She wants to read in a data file from 
the `data` folder inside the `reference` folder. 
- What is her current working directory (as a path)?
- Describe the path that will allow her to access the data, first as a 
relative path, then as an absolute path. 

1. Memory vs disk. 

```{python eval=FALSE}
# read data
# add values
# print the top 10 lines
```

Why is the new table gone when you re-open the spreadsheet on your computer? 
What action would allow you to keep the information from the new table for the future? 
