# RSE Goals {#rse-goals}

This outline describes the questions that the second course will answer.
It assumes learners have completed the novice course, 
which means they know:

-   how to write code (in Python or R) that reads, analyses and plots a dataset,
-   how to write and run unit tests,
-   how to publish a static website using GitHub Pages,
-   how to organize the files in a small project,
-   the basics of licensing, and
-   the basics of good behavior.

## Personas

### Beatrice

**Beatrice** completed a Master's in library science five years ago,
and has worked since then for a small NGO.
She did some statistics during her degree,
and has learned some R and Python by doing data science courses online,
but has no formal training in programming.
Beatrice would like to tidy up the scripts, data sets, and reports she has created
in order to share them with her colleagues.
These lessons will show her how to do this and what "done" looks like.

### Jun

**Jun** completed an Insight Data Science fellowship last year after doing a PhD in Geology,
and now works for a company that does forensic audits.
He has used a variety of machine learning and visualization software,
and has made a few small contributions to a couple of open source R packages.
He would now like to make his own code available to others;
this guide will show him how such projects should be organized.

### Sami

**Sami** learned a fair bit of numerical programming while doing a BSc in applied math,
then started working for the university's supercomputing center.
Over the past few years,
the kinds of applications they are being asked to support have shifted from fluid dynamics to data analysis.
This guide will teach them how to build and run data pipelines
so that they can teach those skills to their users.

## The Unix Shell

Based on <http://swcarpentry.github.io/shell-novice/>
and <https://merely-useful.github.io/still-magic/en/shell.html>

-   How do I navigate my filesystem?
    -   moving about (cd, ls)
    -   files and directories (ls, cp, mkdir, mv, rm)
    -   paths (., .., absolute, relative, special) 
-   How do I examine and/or edit a text file?
    -   difference between text and binary files
    -   running a text editor
    -   operating on text (cat, wc, head, tail, etc)
    -   wildcards
    -   finding things (find, grep, locate)
-   How do I combine multiple commands?
    -   pipes and filters
    -   redirection to/from files
    -   loops
-   Variables
    -   define a variable
    -   use a variable
    -   what's with all the quotes?
-   Shell scripts
    -   read/write/execute file permissions
    -   `#!` lines
    -   using command-line arguments in scripts
    -   job control (&, control-c)
-   Shortcuts
    -   tab completion
    -   previous commands (up arrow, control-r)
    -   history
-   Getting help
    -   --help, man
-   Customising your shell experience
    -   .bashrc
-   Working remotely
    -   scp/rsync and ssh
    -   key pairs
-   Bonus material: non-standard commands you might find useful (tree, htop, autojump, fd, etc)

## Automating analyses

Based on <http://swcarpentry.github.io/make-novice/>
and <https://merely-useful.github.io/still-magic/en/automate.html>

-   How do I write a simple Makefile? 
-   How can I abbreviate the rules in my Makefiles? 
-   How can I write a Makefile to update things when my scripts have changed rather than my input files?
-   How can I define rules to operate on similar files? 
    -   Pattern rules
-   How can I eliminate redundancy in my Makefiles?
    -   Variables
    -   Functions
-   How should I document a Makefile?
-   What other tools can I use?
    -   drake for R
    -   snakemake for Python

## Reusable software

Based on <https://merely-useful.github.io/still-magic/en/configure.html>
and <https://merely-useful.github.io/still-magic/en/logging.html>

-   How do I parse the command line from within a Python script?
    -   basic structure of python scripts
    -   argparse
-   How would I implement a configuration file?
    -   as a data structure (JSON)
    -   as key/value pairs (YAML)
-   How would I report my program's progress?
    -   logging levels
    -   logging channels
    -   configuration
    -   progress bars such as tqdm
-   How do I document my programs?
    -   documentation generators
    -   docstrings in Python
    -   roxygen in R

## Version control

(The novice materials teach it with a GUI.)
Based on <http://swcarpentry.github.io/git-novice/>

-   Version control at the command line
    -   Checking progress: git status, diff, log
    -   Commit cycle: git add, commit, push, pull
-   How do I do multiple things at once?
    -   branches
    -   branch naming
    -   branch management conventions (like feature branches)
-   How do I suggest changes to other people's code?
    -   forking repositories
    -   creating pull requests
    -   reviewing pull requests

## Testing

Based on <http://katyhuff.github.io/python-testing/>,
and <https://merely-useful.github.io/still-magic/en/unit.html>

-   Why should I test my code?
-   How do I implement tests/checks at specific points within my code?
    -   assertions (brief, this is covered in novice course)
    -   exceptions
-   How can I write and manage tests for my software?
    -   unit tests
    -   test runners
-   What tests should I write for my software?
    -   edge cases
    -   fails when it should
    -   bugs become tests
-   How can I run commands automatically every time a repository is updated?
    -   continuous integration
    -   Travis
-   How can I tell what I have and haven't tested?
    -   coverage
-   What *isn't* included?
    -   legal liabilities

## Packaging

Based on <https://carpentrieslab.github.io/python-aos-lesson/01-conda/>
and <https://merely-useful.github.io/still-magic/en/package.html>

-   How do I install and manage my Python environment?
    -   Python distributions (Anaconda)
    -   Package managers (pip, conda)
    -   conda environments
-   How can I write a package that can be installed via pip?
-   How do I write a package that can be shared on CRAN?
-   How do version numbers work?
-   How can I put documentation for my package on the web? (e.g. Sphinx / Read The Docs for Python, pkgdown for R)

## Project management

-   How can **we** keep track of who's doing what and what's still to be done?
    -   issue tracking
    -   issue tagging as lightweight workflow
-   How can **we** figure out what to build next?
    -   planning vs. agile
    -   3x3 prioritization
-   How can **we** make decisions?
    -   how to run a meeting
    -   project governance
    -   strategies for handling difficult project members

## Other topics we have committed to considering 

- SQL: <https://github.com/merely-useful/merely-useful.github.io/issues/70>
- Regular expressions: <https://github.com/merely-useful/merely-useful.github.io/issues/71>
- JSON: <https://github.com/merely-useful/merely-useful.github.io/issues/72>

## What have we left out?

-   Object-oriented programming
-   Nonstandard evaluation (in R)
-   Refactoring
-   Profiling and performance tuning
-   Time management and the effects of overwork
-   Everything with "parallel" in its name...
