# Setting Up {#install}

## Software {#install-software}

In order to complete the activities in this book,
the following software is required:

1. a [Bash shell][shell]
2. [Git][git]
3. a text editor
4. [Python 3][python] (via the Anaconda distribution)
5. [GNU Make][gnu-make]

Software installation instructions for Windows, Mac and Linux operating systems
(with video tutorials) are maintained by [The Carpentries][carpentries]
as part of their workshop website template:
[https://carpentries.github.io/workshop-template/#setup](https://carpentries.github.io/workshop-template/#setup)

Follow those instructions to install the bash shell, Git, a text editor and Anaconda.

If Make is not already installed on your computer (type `make -v` into the Bash shell to check): 

- *Linux (Debian/Ubuntu)*: Install it from the Bash shell using `sudo apt-get install make`.
- *Mac*: Install [Xcode] (via the App Store).
- *Windows*: Follow the [installation instructions][ubc-mds-make-windows] maintained by the
  Master of Data Science at the University of British Columbia.

> **conda in the shell on windows**
>
> If you are using Windows and the `conda` command isn’t available at the Bash shell,
> you’ll need to open the Anaconda Prompt program (via the Windows start menu)
> and run the command `conda init bash` (this only needs to be done once).
> After that, your shell will be configured to use conda going forward.

## Configuring Git to use Nano {#install-git-nano}

To make Git use the Nano editor for writing commit messages,
run the following command:

```shell
git config --global core.editor "nano -w"
```
  
## Data {#install-data}

Download [`zipf.zip`][data-files] and unzip it in the location that you would like
to store the files associated with this book.
When you are done,
you should have a directory called `zipf`,
containing a single sub-directory called `data`
with the following contents:
 
```text
zipf/
└── data
    ├── README.md
    ├── dracula.txt
    ├── frankenstein.txt
    ├── jane_eyre.txt
    ├── moby_dick.txt
    ├── sense_and_sensibility.txt
    ├── sherlock_holmes.txt
    └── time_machine.txt
```

See `data/README.md` for information about the data.
