
## How can I work with two or more datasets?

Often related data exists in multiple files. We often need to combine these
files into a single data frame to analyze the data. You can stack multiple data
frames together using the `concat()` function, and you can also *join* multiple
data frames using a common field.

### Concatenating data frames

Let’s grab two subsets of our data to see how `concat()` works.

```python
# get the first 10 rows
data_subset = dog_licenses.head(10)

# get the last 10 rows
data_subset_last10 = dog_licenses.tail(10)

# Reset the index values to the second data frame appends properly
data_subset_last10=dog_licenses_subset_last10.reset_index(drop=True)
# drop=True option avoids adding new index column with old index values
```

When we concatenate data frames, we need to specify the axis. `axis=0` tells
pandas to stack the second data frame under the first one. It will automatically
detect whether the column names are the same and will stack accordingly. `axis=1`
will stack the columns in the second data frame to the RIGHT of the first
data frame. To stack the data vertically, we need to make sure we have the same
columns and associated column format in both datasets. When we stack
horizonally, we want to make sure what we are doing makes sense (ie the data
are related in some way).

```python
# Stack the data frames on top of each other
vertical_stack = pd.concat([data_subset, data_subset_last10], axis=0)

# Place the data frames side by side
horizontal_stack = pd.concat([data_subset, data_subset_last10], axis=1)
```

### Joining data frames

When we concatenated our data frames we simply added them to each other -
stacking them either vertically or side by side. Another way to combine data
frames is to use columns in each dataset that contain common values (a common
unique id). Combining data frames using a common field is called “joining”. The
columns containing the common values are called “join key(s)”.
