# Key Points {#r-rse-keypoints}

```{r r-rse-keypoints-setup, include=FALSE}
source("_common.R")
```

## The Basics of the Unix Shell
```{r, child="keypoints/rse-bash-basics.md"}
```

## Going Further with the Unix Shell
```{r, child="keypoints/rse-bash-advanced.md"}
```

## Git at the Command Line
```{r, child="keypoints/rse-git-cmdline.md"}
```

## Advanced Git
```{r, child="keypoints/rse-git-advanced.md"}
```

## Code Style, Review, and Refactoring
```{r, child="keypoints/rse-style.md"}
```

## Automating Analyses
```{r, child="keypoints/rse-automate.md"}
```

## Working in Teams
```{r, child="keypoints/rse-teams.md"}
```

## Project Structure
```{r, child="keypoints/rse-project.md"}
```

## Continuous Integration
```{r, child="keypoints/rse-ci.md"}
```

## R Packaging
```{r, child="keypoints/rse-package-r.md"}
```

## Python Packaging
```{r, child="keypoints/rse-package-py.md"}
```

## Correctness
```{r, child="keypoints/rse-correct.md"}
```

## Publishing
```{r, child="keypoints/rse-publish.md"}
```
