<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Data Manipulation | Merely Useful: Novice R</title>
  <meta name="description" content="Chapter 7 Data Manipulation | Merely Useful: Novice R" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Data Manipulation | Merely Useful: Novice R" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="merely-useful/merely-useful.github.io" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Data Manipulation | Merely Useful: Novice R" />
  
  
  

<meta name="author" content="Madeleine Bonsma-Fisher, Kate Hertweck, Damien Irving, Luke Johnston, Christina Koch, Sara Mahallati, Brandeis Marshall, Joel Ostblom, Elizabeth Wickes, Charlotte Wickham, and Greg Wilson" />


<meta name="date" content="2019-11-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="r-reproducibility.html"/>
<link rel="next" href="r-publishing.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">Merely Useful</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#overview-against"><i class="fa fa-check"></i><b>1.1</b> Why isn’t all of this normal already?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#overview-ack"><i class="fa fa-check"></i><b>1.2</b> Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="novice-goals.html"><a href="novice-goals.html"><i class="fa fa-check"></i><b>2</b> Novice Goals</a><ul>
<li class="chapter" data-level="2.1" data-path="novice-goals.html"><a href="novice-goals.html#personas"><i class="fa fa-check"></i><b>2.1</b> Personas</a><ul>
<li class="chapter" data-level="2.1.1" data-path="novice-goals.html"><a href="novice-goals.html#anya"><i class="fa fa-check"></i><b>2.1.1</b> Anya</a></li>
<li class="chapter" data-level="2.1.2" data-path="novice-goals.html"><a href="novice-goals.html#exton"><i class="fa fa-check"></i><b>2.1.2</b> Exton</a></li>
<li class="chapter" data-level="2.1.3" data-path="novice-goals.html"><a href="novice-goals.html#irwin"><i class="fa fa-check"></i><b>2.1.3</b> Irwin</a></li>
<li class="chapter" data-level="2.1.4" data-path="novice-goals.html"><a href="novice-goals.html#camilla"><i class="fa fa-check"></i><b>2.1.4</b> Camilla</a></li>
<li class="chapter" data-level="2.1.5" data-path="novice-goals.html"><a href="novice-goals.html#jordan"><i class="fa fa-check"></i><b>2.1.5</b> Jordan</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="novice-goals.html"><a href="novice-goals.html#getting-started"><i class="fa fa-check"></i><b>2.2</b> Getting started</a></li>
<li class="chapter" data-level="2.3" data-path="novice-goals.html"><a href="novice-goals.html#data-manipulation"><i class="fa fa-check"></i><b>2.3</b> Data manipulation</a></li>
<li class="chapter" data-level="2.4" data-path="novice-goals.html"><a href="novice-goals.html#plotting"><i class="fa fa-check"></i><b>2.4</b> Plotting</a></li>
<li class="chapter" data-level="2.5" data-path="novice-goals.html"><a href="novice-goals.html#development"><i class="fa fa-check"></i><b>2.5</b> Development</a></li>
<li class="chapter" data-level="2.6" data-path="novice-goals.html"><a href="novice-goals.html#data-analysis"><i class="fa fa-check"></i><b>2.6</b> Data analysis</a></li>
<li class="chapter" data-level="2.7" data-path="novice-goals.html"><a href="novice-goals.html#version-control"><i class="fa fa-check"></i><b>2.7</b> Version control</a></li>
<li class="chapter" data-level="2.8" data-path="novice-goals.html"><a href="novice-goals.html#publishing"><i class="fa fa-check"></i><b>2.8</b> Publishing</a></li>
<li class="chapter" data-level="2.9" data-path="novice-goals.html"><a href="novice-goals.html#reproducibility"><i class="fa fa-check"></i><b>2.9</b> Reproducibility</a></li>
<li class="chapter" data-level="2.10" data-path="novice-goals.html"><a href="novice-goals.html#collaboration"><i class="fa fa-check"></i><b>2.10</b> Collaboration</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-intro.html"><a href="r-intro.html"><i class="fa fa-check"></i><b>3</b> Introduction</a><ul>
<li class="chapter" data-level="3.1" data-path="r-intro.html"><a href="r-intro.html#r-intro-personas"><i class="fa fa-check"></i><b>3.1</b> Who are these lessons for?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="r-intro.html"><a href="r-intro.html#exton-excel"><i class="fa fa-check"></i><b>3.1.1</b> Exton Excel</a></li>
<li class="chapter" data-level="3.1.2" data-path="r-intro.html"><a href="r-intro.html#nina-newbie"><i class="fa fa-check"></i><b>3.1.2</b> Nina Newbie</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="r-intro.html"><a href="r-intro.html#r-intro-goals"><i class="fa fa-check"></i><b>3.2</b> What will these lessons teach you?</a><ul>
<li class="chapter" data-level="3.2.1" data-path="r-intro.html"><a href="r-intro.html#r-intro-prereq"><i class="fa fa-check"></i><b>3.2.1</b> What do you need to have and know to start?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="r-intro.html"><a href="r-intro.html#r-intro-example"><i class="fa fa-check"></i><b>3.3</b> What examples will we use?</a></li>
<li class="chapter" data-level="3.4" data-path="r-intro.html"><a href="r-intro.html#whats-the-big-picture-r-intro-bigpicture"><i class="fa fa-check"></i><b>3.4</b> What’s the big picture? (#r-intro-bigpicture}</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="r-getting-started.html"><a href="r-getting-started.html"><i class="fa fa-check"></i><b>4</b> Getting Started with R</a><ul>
<li class="chapter" data-level="4.1" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-questions"><i class="fa fa-check"></i><b>4.1</b> Questions</a></li>
<li class="chapter" data-level="4.2" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-rstudio"><i class="fa fa-check"></i><b>4.2</b> Introduction to RStudio</a></li>
<li class="chapter" data-level="4.3" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-console"><i class="fa fa-check"></i><b>4.3</b> Running Code in the Console</a></li>
<li class="chapter" data-level="4.4" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-script"><i class="fa fa-check"></i><b>4.4</b> Running Code via Scripts</a></li>
<li class="chapter" data-level="4.5" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-objects"><i class="fa fa-check"></i><b>4.5</b> Assigning and Recalling Objects</a></li>
<li class="chapter" data-level="4.6" data-path="r-getting-started.html"><a href="r-getting-started.html#r-viewing-installed-packages"><i class="fa fa-check"></i><b>4.6</b> Viewing installed packages</a></li>
<li class="chapter" data-level="4.7" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-rstudio-help"><i class="fa fa-check"></i><b>4.7</b> Getting Help in RStudio</a></li>
<li class="chapter" data-level="4.8" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-web-help"><i class="fa fa-check"></i><b>4.8</b> Getting Help Online</a></li>
<li class="chapter" data-level="4.9" data-path="r-getting-started.html"><a href="r-getting-started.html#exercises"><i class="fa fa-check"></i><b>4.9</b> Exercises</a></li>
<li class="chapter" data-level="4.10" data-path="r-getting-started.html"><a href="r-getting-started.html#r-getting-started-keypoints"><i class="fa fa-check"></i><b>4.10</b> Key Points</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="practice.html"><a href="practice.html"><i class="fa fa-check"></i><b>5</b> Practice</a><ul>
<li class="chapter" data-level="5.1" data-path="practice.html"><a href="practice.html#working-with-a-single-tidy-table"><i class="fa fa-check"></i><b>5.1</b> Working with a single tidy table</a></li>
<li class="chapter" data-level="5.2" data-path="practice.html"><a href="practice.html#working-with-grouped-data"><i class="fa fa-check"></i><b>5.2</b> Working with grouped data</a></li>
<li class="chapter" data-level="5.3" data-path="practice.html"><a href="practice.html#creating-charts"><i class="fa fa-check"></i><b>5.3</b> Creating charts</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-reproducibility.html"><a href="r-reproducibility.html"><i class="fa fa-check"></i><b>6</b> Reproducibility</a><ul>
<li class="chapter" data-level="6.1" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-reproducibility-projects"><i class="fa fa-check"></i><b>6.1</b> Project organization</a><ul>
<li class="chapter" data-level="6.1.1" data-path="r-reproducibility.html"><a href="r-reproducibility.html#creating-your-first-project"><i class="fa fa-check"></i><b>6.1.1</b> Creating your first project</a></li>
<li class="chapter" data-level="6.1.2" data-path="r-reproducibility.html"><a href="r-reproducibility.html#exercise-better-file-naming"><i class="fa fa-check"></i><b>6.1.2</b> Exercise: Better file naming</a></li>
<li class="chapter" data-level="6.1.3" data-path="r-reproducibility.html"><a href="r-reproducibility.html#should-you-keep-your-data-under-version-control"><i class="fa fa-check"></i><b>6.1.3</b> Should you keep your data under version control?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-reproducibility-reusability"><i class="fa fa-check"></i><b>6.2</b> Reusability</a><ul>
<li class="chapter" data-level="6.2.1" data-path="r-reproducibility.html"><a href="r-reproducibility.html#keeping-a-clean-slate"><i class="fa fa-check"></i><b>6.2.1</b> Keeping a clean slate</a></li>
<li class="chapter" data-level="6.2.2" data-path="r-reproducibility.html"><a href="r-reproducibility.html#packages-data-and-file-paths"><i class="fa fa-check"></i><b>6.2.2</b> Packages, data, and file paths</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-reproducibility-readability"><i class="fa fa-check"></i><b>6.3</b> Readability</a><ul>
<li class="chapter" data-level="6.3.1" data-path="r-reproducibility.html"><a href="r-reproducibility.html#exercise-make-the-code-more-readable"><i class="fa fa-check"></i><b>6.3.1</b> Exercise: Make the code more readable</a></li>
<li class="chapter" data-level="6.3.2" data-path="r-reproducibility.html"><a href="r-reproducibility.html#automatic-styling-with-styler"><i class="fa fa-check"></i><b>6.3.2</b> Automatic styling with styler</a></li>
<li class="chapter" data-level="6.3.3" data-path="r-reproducibility.html"><a href="r-reproducibility.html#exercise-use-styler-to-fix-code-formatting"><i class="fa fa-check"></i><b>6.3.3</b> Exercise: Use styler to fix code formatting</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-reproducibility-markdown"><i class="fa fa-check"></i><b>6.4</b> Integrating text, code, and results</a><ul>
<li class="chapter" data-level="6.4.1" data-path="r-reproducibility.html"><a href="r-reproducibility.html#markdown"><i class="fa fa-check"></i><b>6.4.1</b> Markdown</a></li>
<li class="chapter" data-level="6.4.2" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-markdown"><i class="fa fa-check"></i><b>6.4.2</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-reproducibility-keypoints"><i class="fa fa-check"></i><b>6.5</b> Key Points</a></li>
<li class="chapter" data-level="6.6" data-path="r-reproducibility.html"><a href="r-reproducibility.html#r-reproducibility-resources"><i class="fa fa-check"></i><b>6.6</b> Additional learning resources and material</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html"><i class="fa fa-check"></i><b>7</b> Data Manipulation</a><ul>
<li class="chapter" data-level="7.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#r-data-manipulation-questions"><i class="fa fa-check"></i><b>7.1</b> Questions</a></li>
<li class="chapter" data-level="7.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#motivation"><i class="fa fa-check"></i><b>7.2</b> Motivation</a><ul>
<li class="chapter" data-level="7.2.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-point-and-click-data-manipulation"><i class="fa fa-check"></i><b>7.2.1</b> Exercise: Point and click data manipulation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exploring-data-in-the-console"><i class="fa fa-check"></i><b>7.3</b> Exploring data in the console</a><ul>
<li class="chapter" data-level="7.3.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#re-arranging-rows"><i class="fa fa-check"></i><b>7.3.1</b> Re-arranging rows</a></li>
<li class="chapter" data-level="7.3.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-arranging-character-strings"><i class="fa fa-check"></i><b>7.3.2</b> Exercise: Arranging character strings</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#how-can-i-select-subsets-of-my-data"><i class="fa fa-check"></i><b>7.4</b> How can I select subsets of my data?</a><ul>
<li class="chapter" data-level="7.4.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#selecting-columns"><i class="fa fa-check"></i><b>7.4.1</b> Selecting columns</a></li>
<li class="chapter" data-level="7.4.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-find-the-latest-license-issue-date"><i class="fa fa-check"></i><b>7.4.2</b> Exercise: Find the latest license issue date</a></li>
<li class="chapter" data-level="7.4.3" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#combining-operations-with-the-pipe"><i class="fa fa-check"></i><b>7.4.3</b> Combining operations with the pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="7.4.4" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-reading-aloud"><i class="fa fa-check"></i><b>7.4.4</b> Exercise: Reading aloud</a></li>
<li class="chapter" data-level="7.4.5" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-using-the-pipe"><i class="fa fa-check"></i><b>7.4.5</b> Exercise: Using the pipe</a></li>
<li class="chapter" data-level="7.4.6" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#filtering-to-keep-a-subset-of-rows"><i class="fa fa-check"></i><b>7.4.6</b> Filtering to keep a subset of rows</a></li>
<li class="chapter" data-level="7.4.7" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-enterprising-dogs"><i class="fa fa-check"></i><b>7.4.7</b> Exercise: Enterprising dogs</a></li>
<li class="chapter" data-level="7.4.8" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-expired-licenses"><i class="fa fa-check"></i><b>7.4.8</b> Exercise: Expired Licenses</a></li>
<li class="chapter" data-level="7.4.9" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#more-complicated-expressions"><i class="fa fa-check"></i><b>7.4.9</b> More complicated expressions</a></li>
<li class="chapter" data-level="7.4.10" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-expired-licenses-1"><i class="fa fa-check"></i><b>7.4.10</b> Exercise: Expired Licenses</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#how-can-i-calculate-new-values"><i class="fa fa-check"></i><b>7.5</b> How can I calculate new values?</a><ul>
<li class="chapter" data-level="7.5.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-ages-of-dogs"><i class="fa fa-check"></i><b>7.5.1</b> Exercise: Ages of dogs</a></li>
<li class="chapter" data-level="7.5.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-unknown-breeds"><i class="fa fa-check"></i><b>7.5.2</b> Exercise: Unknown breeds</a></li>
<li class="chapter" data-level="7.5.3" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-name-length"><i class="fa fa-check"></i><b>7.5.3</b> Exercise: Name length</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#how-can-i-tell-whats-gone-wrong-in-my-programs"><i class="fa fa-check"></i><b>7.6</b> How can I tell what’s gone wrong in my programs?</a><ul>
<li class="chapter" data-level="7.6.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#common-syntax-errors"><i class="fa fa-check"></i><b>7.6.1</b> Common syntax errors</a></li>
<li class="chapter" data-level="7.6.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-syntax-errors"><i class="fa fa-check"></i><b>7.6.2</b> Exercise: Syntax errors</a></li>
<li class="chapter" data-level="7.6.3" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#common-runtime-errors"><i class="fa fa-check"></i><b>7.6.3</b> Common runtime errors</a></li>
<li class="chapter" data-level="7.6.4" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-object-not-found"><i class="fa fa-check"></i><b>7.6.4</b> Exercise: <code>object not found</code></a></li>
<li class="chapter" data-level="7.6.5" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#warnings-and-messages"><i class="fa fa-check"></i><b>7.6.5</b> Warnings and messages</a></li>
<li class="chapter" data-level="7.6.6" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#what-do-i-do-when-i-get-an-error-i-cant-fix"><i class="fa fa-check"></i><b>7.6.6</b> What do I do when I get an <code>Error</code> I can’t fix?</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#how-can-i-operate-on-subsets-of-my-data"><i class="fa fa-check"></i><b>7.7</b> How can I operate on subsets of my data?</a><ul>
<li class="chapter" data-level="7.7.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-dog-birth-months"><i class="fa fa-check"></i><b>7.7.1</b> Exercise: Dog birth months</a></li>
<li class="chapter" data-level="7.7.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-order-matters"><i class="fa fa-check"></i><b>7.7.2</b> Exercise: Order matters?</a></li>
<li class="chapter" data-level="7.7.3" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-the-five-boroughs"><i class="fa fa-check"></i><b>7.7.3</b> Exercise: the five boroughs</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#how-can-i-read-my-own-tabular-data-into-r"><i class="fa fa-check"></i><b>7.8</b> How can I read my own tabular data into R?</a><ul>
<li class="chapter" data-level="7.8.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#what-is-tabular-data"><i class="fa fa-check"></i><b>7.8.1</b> What is tabular data?</a></li>
<li class="chapter" data-level="7.8.2" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#importing-csv-data-into-r"><i class="fa fa-check"></i><b>7.8.2</b> Importing CSV data into R</a></li>
<li class="chapter" data-level="7.8.3" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-import-visited.csv"><i class="fa fa-check"></i><b>7.8.3</b> Exercise: Import <code>visited.csv</code></a></li>
<li class="chapter" data-level="7.8.4" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise-import-irs-tax-return-data-for-new-york-city"><i class="fa fa-check"></i><b>7.8.4</b> Exercise: Import IRS tax return data for New York City</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#how-can-i-save-my-results"><i class="fa fa-check"></i><b>7.9</b> How can I save my results?</a><ul>
<li class="chapter" data-level="7.9.1" data-path="r-data-manipulation.html"><a href="r-data-manipulation.html#exercise"><i class="fa fa-check"></i><b>7.9.1</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="r-publishing.html"><a href="r-publishing.html"><i class="fa fa-check"></i><b>8</b> Publishing</a><ul>
<li class="chapter" data-level="8.1" data-path="r-publishing.html"><a href="r-publishing.html#r-publishing-questions"><i class="fa fa-check"></i><b>8.1</b> Questions</a></li>
<li class="chapter" data-level="8.2" data-path="r-publishing.html"><a href="r-publishing.html#why-should-i-share-my-work-on-the-internet"><i class="fa fa-check"></i><b>8.2</b> Why should I share my work on the internet?</a></li>
<li class="chapter" data-level="8.3" data-path="r-publishing.html"><a href="r-publishing.html#what-does-it-take-to-get-a-webpage-online"><i class="fa fa-check"></i><b>8.3</b> What does it take to get a webpage online?</a></li>
<li class="chapter" data-level="8.4" data-path="r-publishing.html"><a href="r-publishing.html#how-do-i-get-my-work-on-the-web"><i class="fa fa-check"></i><b>8.4</b> How do I get my work on the web?</a><ul>
<li class="chapter" data-level="8.4.1" data-path="r-publishing.html"><a href="r-publishing.html#a-starting-point"><i class="fa fa-check"></i><b>8.4.1</b> A starting point</a></li>
<li class="chapter" data-level="8.4.2" data-path="r-publishing.html"><a href="r-publishing.html#html-files"><i class="fa fa-check"></i><b>8.4.2</b> HTML files</a></li>
<li class="chapter" data-level="8.4.3" data-path="r-publishing.html"><a href="r-publishing.html#setting-up-your-repo-to-have-a-web-page"><i class="fa fa-check"></i><b>8.4.3</b> Setting up your repo to have a web page</a></li>
<li class="chapter" data-level="8.4.4" data-path="r-publishing.html"><a href="r-publishing.html#getting-a-default-page-to-display-when-people-visit-the-project-site"><i class="fa fa-check"></i><b>8.4.4</b> Getting a default page to display when people visit the project site</a></li>
<li class="chapter" data-level="8.4.5" data-path="r-publishing.html"><a href="r-publishing.html#what-does-it-take-to-get-your-work-on-a-webpage"><i class="fa fa-check"></i><b>8.4.5</b> What does it take to get your work on a webpage?</a></li>
<li class="chapter" data-level="8.4.6" data-path="r-publishing.html"><a href="r-publishing.html#exercise-customize-index.rmd"><i class="fa fa-check"></i><b>8.4.6</b> Exercise: Customize <code>index.Rmd</code></a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="r-publishing.html"><a href="r-publishing.html#how-do-i-link-to-other-pages-files-or-images"><i class="fa fa-check"></i><b>8.5</b> How do I link to other pages, files or images?</a><ul>
<li class="chapter" data-level="8.5.1" data-path="r-publishing.html"><a href="r-publishing.html#linking-to-other-pages"><i class="fa fa-check"></i><b>8.5.1</b> Linking to other pages</a></li>
<li class="chapter" data-level="8.5.2" data-path="r-publishing.html"><a href="r-publishing.html#exercise-relative-links"><i class="fa fa-check"></i><b>8.5.2</b> Exercise: Relative links</a></li>
<li class="chapter" data-level="8.5.3" data-path="r-publishing.html"><a href="r-publishing.html#exercise-add-links-to-index.html"><i class="fa fa-check"></i><b>8.5.3</b> Exercise: Add links to <code>index.html</code></a></li>
<li class="chapter" data-level="8.5.4" data-path="r-publishing.html"><a href="r-publishing.html#linking-to-sections-within-a-page"><i class="fa fa-check"></i><b>8.5.4</b> Linking to sections within a page</a></li>
<li class="chapter" data-level="8.5.5" data-path="r-publishing.html"><a href="r-publishing.html#exercise-add-and-link-to-a-section-in-report.rmd"><i class="fa fa-check"></i><b>8.5.5</b> Exercise: Add and link to a section in <code>report.Rmd</code></a></li>
<li class="chapter" data-level="8.5.6" data-path="r-publishing.html"><a href="r-publishing.html#including-images"><i class="fa fa-check"></i><b>8.5.6</b> Including images</a></li>
<li class="chapter" data-level="8.5.7" data-path="r-publishing.html"><a href="r-publishing.html#exercise-add-an-image-to-index.html"><i class="fa fa-check"></i><b>8.5.7</b> Exercise: Add an image to <code>index.html</code></a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="r-publishing.html"><a href="r-publishing.html#exercise-add-a-website-to-an-existing-project"><i class="fa fa-check"></i><b>8.6</b> Exercise: Add a website to an existing project</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i><b>A</b> License</a></li>
<li class="chapter" data-level="B" data-path="conduct.html"><a href="conduct.html"><i class="fa fa-check"></i><b>B</b> Code of Conduct</a><ul>
<li class="chapter" data-level="B.1" data-path="conduct.html"><a href="conduct.html#conduct-standards"><i class="fa fa-check"></i><b>B.1</b> Our Standards</a></li>
<li class="chapter" data-level="B.2" data-path="conduct.html"><a href="conduct.html#conduct-responsibilities"><i class="fa fa-check"></i><b>B.2</b> Our Responsibilities</a></li>
<li class="chapter" data-level="B.3" data-path="conduct.html"><a href="conduct.html#conduct-scope"><i class="fa fa-check"></i><b>B.3</b> Scope</a></li>
<li class="chapter" data-level="B.4" data-path="conduct.html"><a href="conduct.html#conduct-enforcement"><i class="fa fa-check"></i><b>B.4</b> Enforcement</a></li>
<li class="chapter" data-level="B.5" data-path="conduct.html"><a href="conduct.html#conduct-attribution"><i class="fa fa-check"></i><b>B.5</b> Attribution</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="contributing.html"><a href="contributing.html"><i class="fa fa-check"></i><b>C</b> Contributing</a><ul>
<li class="chapter" data-level="C.1" data-path="contributing.html"><a href="contributing.html#contributing-style"><i class="fa fa-check"></i><b>C.1</b> Style Guide</a></li>
<li class="chapter" data-level="C.2" data-path="contributing.html"><a href="contributing.html#setting-up"><i class="fa fa-check"></i><b>C.2</b> Setting Up</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="glossary.html"><a href="glossary.html"><i class="fa fa-check"></i><b>D</b> Glossary</a></li>
<li class="chapter" data-level="E" data-path="objectives.html"><a href="objectives.html"><i class="fa fa-check"></i><b>E</b> Novice R Learning Objectives</a></li>
<li class="chapter" data-level="F" data-path="keypoints.html"><a href="keypoints.html"><i class="fa fa-check"></i><b>F</b> Novice R Key Points</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Merely Useful: Novice R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="r-data-manipulation" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Data Manipulation</h1>
<div id="r-data-manipulation-questions" class="section level2">
<h2><span class="header-section-number">7.1</span> Questions</h2>
<ul>
<li>How can I read tabular data into a program?</li>
<li>How can I select subsets of my data?</li>
<li>How can I calculate new values?</li>
<li>How can I tell what’s gone wrong in my programs?</li>
<li>How can I operate on subsets of my data?</li>
<li>How can I save my results?</li>
</ul>
</div>
<div id="motivation" class="section level2">
<h2><span class="header-section-number">7.2</span> Motivation</h2>
<p>FIXME: where is data introduced?</p>
<p>FIXME: clean version with no missing values and snake case column names, including month and year columns for some (all?) of the date columns.</p>
<p>FIXME: I’m assuming that at some point this data will live in R package, so we can delay importing data to end of chapter.</p>
<p>The RStudio Viewer has an interface much like other spreadsheet programs you might have used. You can use this Viewer to look at the <code>dog_licenses</code> tibble with the <code>View()</code> function:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" data-line-number="1"><span class="kw">View</span>(dog_licenses)</a></code></pre></div>
<p><img src="figures/r-data-manipulation/dog-licenses-view.png" /></p>
<p>This viewer has some basic data manipulation features:</p>
<ul>
<li><p><strong>Arrange</strong> You can change the order of the rows in the data based on the values in a column by clicking the up/down arrow next to the column name.</p></li>
<li><p><strong>Filter</strong> You can filter to include only rows which have a certain value in a column by first clicking the small funnel icon labelled “Filter”, then typing a desired value in the appropriate column.</p></li>
</ul>
<p>Arrange and filter are known as data manipulation <strong>verbs</strong>. Individually, they describe a single simple manipulation of a dataset. It’s surprising how many questions you can answer using just these two basic verbs:</p>
<ul>
<li><p>How old is the oldest dog in this data? To answer we can arrange the <code>animal_birth_month</code> column in increasing order and see Jack, a Pug from Queens, was born in January 1999 (this license was issued in May 2015, making Jack at least 16 at the time). You’ll notice that there are other dogs with this same birthday.</p></li>
<li><p>What range of license issue dates are in this data? Arrange <code>license_issued_date</code> once in increasing order and once in decreasing order, to find the issue dates range from 12th September 2015 to 31st December 2016.</p></li>
<li><p>How many dogs licenses belong to dogs named Fido? Filter the <code>animal_name</code> column with <code>Fido</code>, and see “Showing … of 12 entries” - so 12!</p></li>
<li><p>and many more…</p></li>
</ul>
<p>While these verbs are powerful in their own right, their real power comes from combining them. For example, we can answer the more complicated question “Which dog named Fido is the oldest?” by first filtering then arranging.</p>
<p>The Viewer in RStudio, however, has two huge limitations:</p>
<ul>
<li><p>It’s a point and click interface. This means to repeat the same operation again you need to remember exactly the steps of point, clicking and typing you performed to get to your answer. Consequently, it’s hard to share those steps unambiguously with someone else, and it’s hard to save your results for future.</p></li>
<li><p>The manipulation verbs in the viewer are limited. There is no way to rearrange the columns, add new variables or calculate summaries like counts or averages.</p></li>
</ul>
<p>You’ll start this chapter by overcoming this first limitation. You won’t use the Viewer to arrange and filter, you’ll learn to write code to do the same operations. Then you’ll increase your vocabulary of data manipulation verbs to include:</p>
<ul>
<li>selecting variables,</li>
<li>adding variables,</li>
<li>summarizing rows, and</li>
<li>performing these operations on subsets of the data.</li>
</ul>
<p>Combining these verbs you’ll be able to answers questions like:</p>
<ul>
<li><p>How long are licences issued for?</p></li>
<li><p>What are the most popular breeds?</p></li>
<li><p>What names are most popular for licensed dogs in New York? Does this very geographically?</p></li>
<li><p>When are dogs born?</p></li>
</ul>
<p>FIXME: update these question to reflect things that are actually done in this and later chapters.</p>
<p>To master data manipulation you need to master two pieces:</p>
<ul>
<li><p>How to describe the action you want with the data manipulation verbs individually. This is a language specific skill - in this chapter, you’ll use the functions in the dplyr package.</p></li>
<li><p>Identifying which verbs, and in which order to apply them, to answer a question of interest. This skill will translate across all technologies, but it takes a little longer to master.</p></li>
</ul>
<div id="exercise-point-and-click-data-manipulation" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Exercise: Point and click data manipulation</h3>
<p>Using the RStudio Viewer answer the following questions:</p>
<ul>
<li>How many dog licenses belong to dogs named “Queen” that live in “Queens”?</li>
</ul>
</div>
</div>
<div id="exploring-data-in-the-console" class="section level2">
<h2><span class="header-section-number">7.3</span> Exploring data in the console</h2>
<p>Let’s take a look at the data in the console:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" data-line-number="1">dog_licenses</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1        533 BONITA      F             2013-05-01 00:00:00 Unknown   
##  2        548 ROCKY       M             2014-05-01 00:00:00 Labrador …
##  3        622 BULLY       M             2010-07-01 00:00:00 American …
##  4        633 COCO        M             2005-02-01 00:00:00 Labrador …
##  5        655 SKI         F             2012-09-01 00:00:00 American …
##  6        872 CHASE       M             2013-11-01 00:00:00 Shih Tzu  
##  7        874 CHEWY       M             2014-09-01 00:00:00 Shih Tzu  
##  8        875 CHASE       M             2008-08-01 00:00:00 Labrador …
##  9        893 MILEY       F             2008-07-01 00:00:00 Boxer     
## 10        919 KENZI       F             2010-05-01 00:00:00 Schnauzer…
## # … with 118,532 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>Notice that in contrast to the Viewer you only see the first 10 rows of the dataset, and just the first few columns. The number of columns you see depends on the width of your console, so you may see more or fewer than displayed here. You should also note some of the contents of the columns have been abbreviated. The <code>…</code> at the end of some values in <code>breed_name</code> indicates these values have been truncated for display purposes.</p>
<p>You’ll be using the dplyr package for data manipulation. Since it is part of the tidyverse, you’ll need to load the tidyverse package to begin:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="re-arranging-rows" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Re-arranging rows</h3>
<p>You can reorder rows of data with the dplyr function <code>arrange()</code>. The arrange function takes a tibble as its first argument and column names as the remaining arguments. The result will have the rows ordered in increasing value of the specified column. For example, to find the licenses belonging to the oldest dogs we arrange <code>dog_licenses</code> using the <code>animal_birth_month</code> column:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" data-line-number="1"><span class="kw">arrange</span>(dog_licenses, animal_birth_month)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1      15568 JACK        M             1999-01-01 00:00:00 Pug       
##  2      23695 KATTY       F             1999-01-01 00:00:00 Chihuahua 
##  3     101309 TOMMY       M             1999-01-01 00:00:00 Unknown   
##  4       1598 SARAH       F             1999-01-01 00:00:00 West High…
##  5       8628 DOMINO      M             1999-01-01 00:00:00 Labrador …
##  6      15733 BRINKS      M             1999-01-01 00:00:00 Yorkshire…
##  7      30419 LUCKY       M             1999-01-01 00:00:00 Unknown   
##  8      31348 MAGGIE      F             1999-01-01 00:00:00 German Sh…
##  9      34685 COOKIE      M             1999-01-01 00:00:00 Pomeranian
## 10      37194 DARCY       F             1999-01-01 00:00:00 Cocker Sp…
## # … with 118,532 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>You’ll see Jack the Pug that lives in Queens, just like you did in the Viewer.</p>
<p>To arrange the rows by decreasing value, you need to wrap the column name in <code>desc()</code> (short for <em>desc</em>ending order). For instance to find the youngest dogs:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" data-line-number="1"><span class="kw">arrange</span>(dog_licenses, <span class="kw">desc</span>(animal_birth_month))</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1     120352 MARLEY      M             2016-12-01 00:00:00 Cocker Sp…
##  2     121981 MR.         M             2016-12-01 00:00:00 Chihuahua…
##  3     120501 RORY        M             2016-12-01 00:00:00 Unknown   
##  4     122028 TAQUITO     M             2016-12-01 00:00:00 Papillon  
##  5     115820 REX         M             2016-11-01 00:00:00 Maltese   
##  6     121727 CHANDERBAL… M             2016-11-01 00:00:00 Havanese  
##  7     115777 ANGEL       F             2016-11-01 00:00:00 Poodle, M…
##  8     118175 MASON       M             2016-11-01 00:00:00 American …
##  9     121601 TEDDY       M             2016-11-01 00:00:00 Havanese  
## 10     120995 LOLA        F             2016-11-01 00:00:00 Morkie    
## # … with 118,532 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>As another example, to find the earliest issue date we can order by increasing <code>license_issued_date</code>:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" data-line-number="1"><span class="kw">arrange</span>(dog_licenses, license_issued_date)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1          1 QUEEN       F             2013-04-01 00:00:00 Akita Cro…
##  2          2 CHEWBACCA   F             2012-06-01 00:00:00 Labrador …
##  3          3 IAN         M             2006-01-01 00:00:00 Unknown   
##  4          7 LOLA        F             2009-06-01 00:00:00 Maltese   
##  5          4 PAIGE       F             2014-07-01 00:00:00 American …
##  6          5 BUDDY       M             2008-04-01 00:00:00 Unknown   
##  7          8 YOGI        M             2010-09-01 00:00:00 Boxer     
##  8         10 MUNECA      F             2013-05-01 00:00:00 Beagle    
##  9         27 BESS        F             2010-09-01 00:00:00 Beagle    
## 10         26 BIGS        M             2004-12-01 00:00:00 American …
## # … with 118,532 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>The first row is the record with the earliest issue date, but we can’t actually see that date because the column <code>license_issued_date</code> isn’t being displayed due to space. One solution is to extract only the columns we are interested in, a manipulation known as selecting columns.</p>
</div>
<div id="exercise-arranging-character-strings" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Exercise: Arranging character strings</h3>
<p>Use <code>arrange()</code> to order the dog licenses by <code>animal_name</code> in increasing order. What does this tell you about the way R treats punctuation and numbers when dealing with alphabetical order?</p>
</div>
</div>
<div id="how-can-i-select-subsets-of-my-data" class="section level2">
<h2><span class="header-section-number">7.4</span> How can I select subsets of my data?</h2>
<p>Two verbs are used to subset data:</p>
<ul>
<li><code>select()</code> to select columns</li>
<li><code>filter()</code> to select rows</li>
</ul>
<p>You’ll learn about these two functions in this section, along with learning about a way to chain together multiple operations on a dataset.</p>
<div id="selecting-columns" class="section level3">
<h3><span class="header-section-number">7.4.1</span> Selecting columns</h3>
<p>The <code>select()</code> function in dplyr is used to extract some subset of columns (but keep all the rows) from a tibble. Just like <code>arrange()</code>, it takes a tibble as its first argument and column names as the remaining arguments. For example, to keep only the <code>animal_name</code> column:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" data-line-number="1"><span class="kw">select</span>(dog_licenses, animal_name)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 1
##    animal_name
##    &lt;chr&gt;      
##  1 BONITA     
##  2 ROCKY      
##  3 BULLY      
##  4 COCO       
##  5 SKI        
##  6 CHASE      
##  7 CHEWY      
##  8 CHASE      
##  9 MILEY      
## 10 KENZI      
## # … with 118,532 more rows</code></pre>
<p>You can provide additional column names as arguments to keep additional specified columns, for example to keep <code>animal_name</code> and <code>breed_name</code>:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" data-line-number="1"><span class="kw">select</span>(dog_licenses, animal_name, breed_name)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 2
##    animal_name breed_name                        
##    &lt;chr&gt;       &lt;chr&gt;                             
##  1 BONITA      Unknown                           
##  2 ROCKY       Labrador Retriever Crossbreed     
##  3 BULLY       American Pit Bull Terrier/Pit Bull
##  4 COCO        Labrador Retriever                
##  5 SKI         American Pit Bull Terrier/Pit Bull
##  6 CHASE       Shih Tzu                          
##  7 CHEWY       Shih Tzu                          
##  8 CHASE       Labrador Retriever                
##  9 MILEY       Boxer                             
## 10 KENZI       Schnauzer, Miniature              
## # … with 118,532 more rows</code></pre>
<p>To return to finding the earliest issue date, you need to first arrange by increasing <code>license_issued_date</code> and then select the <code>license_issued_date</code> column. One approach is to store the result of the arrange step,</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" data-line-number="1">dog_by_date &lt;-<span class="st"> </span><span class="kw">arrange</span>(dog_licenses, license_issued_date)</a></code></pre></div>
<p>Then apply the select step to this object:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" data-line-number="1"><span class="kw">select</span>(dog_by_date, license_issued_date)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 1
##    license_issued_date
##    &lt;date&gt;             
##  1 2014-09-12         
##  2 2014-09-12         
##  3 2014-09-12         
##  4 2014-09-12         
##  5 2014-09-12         
##  6 2014-09-12         
##  7 2014-09-12         
##  8 2014-09-13         
##  9 2014-09-13         
## 10 2014-09-13         
## # … with 118,532 more rows</code></pre>
<p>There are lots of shortcuts you can use with <code>select()</code> to avoid having to type out all the variables you want to keep. For example, you can ask for all the columns that start with a certain string:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb164-1" data-line-number="1"><span class="kw">select</span>(dog_licenses, <span class="kw">starts_with</span>(<span class="st">&quot;Animal&quot;</span>))</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 3
##    animal_name animal_gender animal_birth_month 
##    &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;             
##  1 BONITA      F             2013-05-01 00:00:00
##  2 ROCKY       M             2014-05-01 00:00:00
##  3 BULLY       M             2010-07-01 00:00:00
##  4 COCO        M             2005-02-01 00:00:00
##  5 SKI         F             2012-09-01 00:00:00
##  6 CHASE       M             2013-11-01 00:00:00
##  7 CHEWY       M             2014-09-01 00:00:00
##  8 CHASE       M             2008-08-01 00:00:00
##  9 MILEY       F             2008-07-01 00:00:00
## 10 KENZI       F             2010-05-01 00:00:00
## # … with 118,532 more rows</code></pre>
<p>Take a look in the <a href="https://dplyr.tidyverse.org/reference/select.html#useful-functions">“Useful functions”</a> section of the <code>select()</code> help page for a complete list:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1">?dplyr<span class="op">::</span>select</a></code></pre></div>
</div>
<div id="exercise-find-the-latest-license-issue-date" class="section level3">
<h3><span class="header-section-number">7.4.2</span> Exercise: Find the latest license issue date</h3>
<p>Combine <code>arrange()</code> and <code>select()</code> to confirm the last issue date in this dataset is 31st December 2016.</p>
</div>
<div id="combining-operations-with-the-pipe" class="section level3">
<h3><span class="header-section-number">7.4.3</span> Combining operations with the pipe <code>%&gt;%</code></h3>
<p>You’ve seen you can combine data manipulation steps to do more complicated tasks, but so far you’ve done so by saving an intermediate object, in our previous example the object <code>dog_by_date</code>:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" data-line-number="1">dog_by_date &lt;-<span class="st"> </span><span class="kw">arrange</span>(dog_licenses, license_issued_date)</a>
<a class="sourceLine" id="cb167-2" data-line-number="2"><span class="kw">select</span>(dog_by_date, license_issued_date)</a></code></pre></div>
<p>The pipe, <code>%&gt;%</code>, is an operator that allows you to chain together operations without intermediate objects and maintain readability. The name, “pipe”, comes from the plumbing kind of pipe, not the smoking kind, and references the idea of objects flowing out of one function and into another. Let’s just look at the first step in our manipulation:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" data-line-number="1"><span class="kw">arrange</span>(dog_licenses, license_issued_date)</a></code></pre></div>
<p>With the pipe this can be rewritten as:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(license_issued_date)</a></code></pre></div>
<p>The pipe takes the object on the left hand side and passes it as the first argument to the function on the right hand side. So, here the <code>dog_licenses</code> dataset is passed to the first argument of <code>arrange()</code>. Inside <code>arrange()</code> we can then list any additional arguments as we normally would.</p>
<p>The pipe works very nicely with the data manipulation verbs because every verb expects a tibble as its first argument and returns a tibble. This means the result of one operation is easily piped into the next operation, allowing you to chain together multiple steps. For instance, piping the result of the arrange step above into the <code>select()</code> function:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb170-2" data-line-number="2"><span class="st">  </span><span class="kw">arrange</span>(license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb170-3" data-line-number="3"><span class="st">  </span><span class="kw">select</span>(license_issued_date)</a></code></pre></div>
<p>When you see the pipe, read it as “and then”. So, the above code would be read:</p>
<blockquote>
<p>Take the dog_licenses data, <strong>and then</strong>
arrange the rows by the <code>license_issued_date</code>, <strong>and then</strong>
select the column <code>license_issued_date</code>.</p>
</blockquote>
<p>The result is code that matches very closely how we might describe the steps we performed in natural language. It’s so natural that for the remainder of the chapter we’ll use the pipe when combining data manipulation steps.</p>
</div>
<div id="exercise-reading-aloud" class="section level3">
<h3><span class="header-section-number">7.4.4</span> Exercise: Reading aloud</h3>
<p>Read the following code aloud to your neighbor (or cat, dog, or <a href="https://en.wikipedia.org/wiki/Rubber_duck_debugging">rubber duck</a>). Remember to pronounce <code>%&gt;%</code> as “and then”.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb171-2" data-line-number="2"><span class="st">  </span><span class="kw">arrange</span>(license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb171-3" data-line-number="3"><span class="st">  </span><span class="kw">select</span>(license_expired_date)</a></code></pre></div>
<p>What question might it answer?</p>
</div>
<div id="exercise-using-the-pipe" class="section level3">
<h3><span class="header-section-number">7.4.5</span> Exercise: Using the pipe</h3>
<p>Re-write this snippet of code to use the pipe:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1"><span class="kw">select</span>(dog_licenses, animal_name, breed_name)</a></code></pre></div>
<p>Use the pipe to re-write this snippet of code to avoid the intermediate variable:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" data-line-number="1">name_and_breed &lt;-<span class="st"> </span><span class="kw">select</span>(dog_licenses, animal_name, breed_name)</a>
<a class="sourceLine" id="cb173-2" data-line-number="2"><span class="kw">arrange</span>(name_and_breed, breed_name)</a></code></pre></div>
</div>
<div id="filtering-to-keep-a-subset-of-rows" class="section level3">
<h3><span class="header-section-number">7.4.6</span> Filtering to keep a subset of rows</h3>
<p>The function to filter rows of a tibble is <code>filter()</code>. Like <code>arrange()</code> and <code>select()</code>, its first argument is a tibble. The remaining arguments describe which rows to <strong>keep</strong>. The rows to keep are specified with a logical expression - something that is either <code>TRUE</code> or <code>FALSE</code>. The rows where this expression is <code>TRUE</code> will be returned.</p>
<p>One of the simplest kinds of logical expression is a test for equality with the <code>==</code> operator. For example, to keep the rows where <code>animal_name</code> is <code>BRUNO</code> you could do:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(animal_name <span class="op">==</span><span class="st"> &quot;BRUNO&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 272 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1      12001 BRUNO       M             2010-05-01 00:00:00 American …
##  2      27228 BRUNO       M             2013-07-01 00:00:00 Jack Russ…
##  3      68192 BRUNO       M             2002-01-01 00:00:00 Shih Tzu  
##  4      70175 BRUNO       M             2015-12-01 00:00:00 Chihuahua…
##  5     120562 BRUNO       M             2016-05-01 00:00:00 Labrador …
##  6       3915 BRUNO       M             2014-03-01 00:00:00 Doberman …
##  7       9614 BRUNO       M             2014-12-01 00:00:00 Boxer     
##  8      15606 BRUNO       M             2015-02-01 00:00:00 French Bu…
##  9      32742 BRUNO       M             2014-03-01 00:00:00 Maltipoo  
## 10      34299 BRUNO       M             2003-01-01 00:00:00 Unknown   
## # … with 262 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>You could read this code aloud as:</p>
<blockquote>
<p>Take the dog_licenses data, <strong>and then</strong>
filter for only rows when <code>animal_name</code> is equal to “BRUNO”</p>
</blockquote>
<p>The logical expression, <code>animal_name == &quot;BRUNO&quot;</code>, will be <code>TRUE</code> when the value of the <code>animal_name</code> column is exactly equal to the character string <code>&quot;BRUNO&quot;</code> - any differences in characters, case, or whitespace will result in <code>FALSE</code>.</p>
<p>Above, each value within a column was compared against the same fixed string (<code>&quot;BRUNO&quot;</code>). You can also compare the values from two columns against each other by including a column name on each side of the <code>==</code> sign. In programming terms this is known as element-wise comparison. For example, <code>license_issued_date == animal_birth_month</code> will return <code>TRUE</code> for a row only if for that row the date the license was issued is the exact same date as the birth month for the dog. If you take a look:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb176-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(license_issued_date <span class="op">==</span><span class="st"> </span>animal_birth_month)</a></code></pre></div>
<pre><code>## # A tibble: 0 x 15
## # … with 15 variables: row_number &lt;dbl&gt;, animal_name &lt;chr&gt;,
## #   animal_gender &lt;chr&gt;, animal_birth_month &lt;dttm&gt;, breed_name &lt;chr&gt;,
## #   borough &lt;chr&gt;, zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;,
## #   census_tract_2010 &lt;dbl&gt;, neighborhood_tabulation_area &lt;chr&gt;,
## #   city_council_district &lt;dbl&gt;, congressional_district &lt;dbl&gt;,
## #   state_senatorial_district &lt;dbl&gt;, license_issued_date &lt;date&gt;,
## #   license_expired_date &lt;date&gt;</code></pre>
<p>There is no output (apart from the column names), which means that no rows satisfy this criteria.</p>
<p>Remember that a string is surrounded by quotes while a column name is not. When you are reading code, look for the quotes to figure out if the comparison is to a string, or (by the absence of quotes) to the strings within a column. Use the same strategy to figure out where the quotes should be in your own code, but beware: misplacing quotes often won’t result in an error, but instead a result that you weren’t expecting. For example, I might be interested in the licenses issued to male dogs and try:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb178-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(<span class="st">&quot;animal_gender&quot;</span> <span class="op">==</span><span class="st"> &quot;M&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 0 x 15
## # … with 15 variables: row_number &lt;dbl&gt;, animal_name &lt;chr&gt;,
## #   animal_gender &lt;chr&gt;, animal_birth_month &lt;dttm&gt;, breed_name &lt;chr&gt;,
## #   borough &lt;chr&gt;, zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;,
## #   census_tract_2010 &lt;dbl&gt;, neighborhood_tabulation_area &lt;chr&gt;,
## #   city_council_district &lt;dbl&gt;, congressional_district &lt;dbl&gt;,
## #   state_senatorial_district &lt;dbl&gt;, license_issued_date &lt;date&gt;,
## #   license_expired_date &lt;date&gt;</code></pre>
<p>The result has zero rows, which would suggest there are no such licenses, but in fact this is the answer to a different question. Can you see what is wrong with the code? By surrounding <code>animal_gender</code> in quotes, R has interpreted the comparison as: is the string <code>&quot;animal_gender&quot;</code> equal to the string <code>&quot;M&quot;</code>?. The answer is <code>FALSE</code>, and no rows are returned. I actually wanted to compare the <code>animal_gender</code> column to the string <code>&quot;M&quot;</code>, so <code>animal_gender</code> should have no quotes around it:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb180-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(animal_gender <span class="op">==</span><span class="st"> &quot;M&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 64,770 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1        548 ROCKY       M             2014-05-01 00:00:00 Labrador …
##  2        622 BULLY       M             2010-07-01 00:00:00 American …
##  3        633 COCO        M             2005-02-01 00:00:00 Labrador …
##  4        872 CHASE       M             2013-11-01 00:00:00 Shih Tzu  
##  5        874 CHEWY       M             2014-09-01 00:00:00 Shih Tzu  
##  6        875 CHASE       M             2008-08-01 00:00:00 Labrador …
##  7        976 APOLLO      M             2014-10-01 00:00:00 American …
##  8       1297 JERRY       M             2009-06-01 00:00:00 Labrador …
##  9       2133 SIMON       M             2010-12-01 00:00:00 Havanese  
## 10       2289 BUDDY       M             2012-06-01 00:00:00 Labrador …
## # … with 64,760 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>The operator, <code>==</code> (you can read as “is equal to”, or simply “equals”), is a specific kind of comparison. Other comparisons include:</p>
<table>
<thead>
<tr class="header">
<th align="left">Operator</th>
<th align="left">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>&lt;</code></td>
<td align="left">less than</td>
</tr>
<tr class="even">
<td align="left"><code>&gt;</code></td>
<td align="left">greater than</td>
</tr>
<tr class="odd">
<td align="left"><code>&lt;=</code></td>
<td align="left">less than or equal to</td>
</tr>
<tr class="even">
<td align="left"><code>&gt;=</code></td>
<td align="left">greater than or equal to</td>
</tr>
<tr class="odd">
<td align="left"><code>!=</code></td>
<td align="left">not equal to</td>
</tr>
</tbody>
</table>
</div>
<div id="exercise-enterprising-dogs" class="section level3">
<h3><span class="header-section-number">7.4.7</span> Exercise: Enterprising dogs</h3>
<p>Are there any dogs called “Spock”, “Picard”, or “Janeway”?</p>
<p>These are Star Trek characters, can you find any dogs with a name from one of your favorite books, TV shows, or movies?</p>
</div>
<div id="exercise-expired-licenses" class="section level3">
<h3><span class="header-section-number">7.4.8</span> Exercise: Expired Licenses</h3>
<p>This code creates a variable that contains the date for the start of the year 2016:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" data-line-number="1">start_of_<span class="dv">2016</span> &lt;-<span class="st"> </span><span class="kw">as.Date</span>(<span class="st">&quot;2016-01-01&quot;</span>)</a></code></pre></div>
<p>Use <code>filter()</code> with this variable to find:</p>
<ul>
<li>The dog licenses that were issued before 2016</li>
<li>The dog licenses that expire before 2016</li>
</ul>
</div>
<div id="more-complicated-expressions" class="section level3">
<h3><span class="header-section-number">7.4.9</span> More complicated expressions</h3>
<p>Logical expressions can be combined with logical operators to construct more complicated expressions. For example, the AND operator, <code>&amp;</code>, returns <code>TRUE</code> only if the expressions on both sides of it are <code>TRUE</code>. For example, you’ve seen, you can find the licenses to dogs called <code>&quot;BRUNO&quot;</code>:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb183-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(animal_name <span class="op">==</span><span class="st"> &quot;BRUNO&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 272 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1      12001 BRUNO       M             2010-05-01 00:00:00 American …
##  2      27228 BRUNO       M             2013-07-01 00:00:00 Jack Russ…
##  3      68192 BRUNO       M             2002-01-01 00:00:00 Shih Tzu  
##  4      70175 BRUNO       M             2015-12-01 00:00:00 Chihuahua…
##  5     120562 BRUNO       M             2016-05-01 00:00:00 Labrador …
##  6       3915 BRUNO       M             2014-03-01 00:00:00 Doberman …
##  7       9614 BRUNO       M             2014-12-01 00:00:00 Boxer     
##  8      15606 BRUNO       M             2015-02-01 00:00:00 French Bu…
##  9      32742 BRUNO       M             2014-03-01 00:00:00 Maltipoo  
## 10      34299 BRUNO       M             2003-01-01 00:00:00 Unknown   
## # … with 262 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>And you could find the dog licenses issued to dogs that live in Brooklyn:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb185-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(borough <span class="op">==</span><span class="st"> &quot;Brooklyn&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 29,334 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1       2895 FUDGE       M             2014-07-01 00:00:00 American …
##  2       4057 STAR        F             2011-01-01 00:00:00 Poodle    
##  3      74463 MUNECA      F             2011-09-01 00:00:00 Chihuahua…
##  4      76232 KATTY       F             2002-06-01 00:00:00 Chihuahua 
##  5      85113 SHADOW      M             2015-03-01 00:00:00 American …
##  6      85997 SPARKIE     M             2013-08-01 00:00:00 Maltese C…
##  7      92451 SNOW        M             2014-07-01 00:00:00 Maltese   
##  8     104256 BELLA       F             2016-07-01 00:00:00 Maltese   
##  9      10389 SPARKLE     F             2006-01-01 00:00:00 Schnauzer…
## 10      82492 UNKNOWN     F             2015-11-01 00:00:00 Pomeranian
## # … with 29,324 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>If you want to find the licenses that are to dogs named Bruno in Brooklyn, you could combine the two logical statements with <code>&amp;</code>:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>((animal_name <span class="op">==</span><span class="st"> &quot;BRUNO&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>(borough <span class="op">==</span><span class="st"> &quot;Brooklyn&quot;</span>))</a></code></pre></div>
<pre><code>## # A tibble: 55 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1       8496 BRUNO       M             2005-04-01 00:00:00 American …
##  2      65466 BRUNO       M             2012-11-01 00:00:00 Golden Re…
##  3     115999 BRUNO       M             2009-01-01 00:00:00 Pug       
##  4     118963 BRUNO       M             2005-01-01 00:00:00 Unknown   
##  5      10505 BRUNO       M             2006-04-01 00:00:00 Bull Dog,…
##  6      14444 BRUNO       M             2007-01-01 00:00:00 Cocker Sp…
##  7      14690 BRUNO       M             2014-04-01 00:00:00 Shih Tzu  
##  8      47454 BRUNO       M             2011-06-01 00:00:00 Pug       
##  9      58918 BRUNO       M             2006-04-01 00:00:00 Bull Dog,…
## 10     105964 BRUNO       M             2016-04-01 00:00:00 Bull Dog,…
## # … with 45 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>The parentheses around each logical expression are optional, but can help visually to group the components to <code>&amp;</code>, especially if those logical expressions get more complicated.</p>
<p>If you want to create an “or” type expression, like “licenses to dogs named BRUNO <strong>or</strong> dogs named BRUCE”, you need to combine two comparisons with the OR operator, <code>|</code>.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb189-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>((animal_name <span class="op">==</span><span class="st"> &quot;BRUNO&quot;</span>) <span class="op">|</span><span class="st"> </span>(animal_name <span class="op">==</span><span class="st"> &quot;BRUCE&quot;</span>))</a></code></pre></div>
<p>If you find yourself combining lots of comparisons on the same column with <code>|</code>, like dogs named <code>BRUNO</code>, <code>BRUCE</code> or <code>BRADY</code>:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb190-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>((animal_name <span class="op">==</span><span class="st"> &quot;BRUNO&quot;</span>) <span class="op">|</span><span class="st"> </span>(animal_name <span class="op">==</span><span class="st"> &quot;BRUCE&quot;</span>) <span class="op">|</span><span class="st"> </span>(animal_name <span class="op">==</span><span class="st"> &quot;BRADY&quot;</span>))</a></code></pre></div>
<p>You can save a lot of typing with <code>%in%</code>:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb191-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(animal_name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;BRUNO&quot;</span>, <span class="st">&quot;BRUCE&quot;</span>, <span class="st">&quot;BRADY&quot;</span>))</a></code></pre></div>
<p>On the right hand side of <code>%in%</code> the function <code>c()</code>, <strong>c</strong>ombines many single values into a vector. <code>%in%</code> will return <code>TRUE</code> for an element of the left hand side if it is contained in the vector on the right hand side.</p>
</div>
<div id="exercise-expired-licenses-1" class="section level3">
<h3><span class="header-section-number">7.4.10</span> Exercise: Expired Licenses</h3>
<p>This code creates two variables that contain the dates for the start and end of the year 2016:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" data-line-number="1">start_of_<span class="dv">2016</span> &lt;-<span class="st"> </span><span class="kw">as.Date</span>(<span class="st">&quot;2016-01-01&quot;</span>)</a>
<a class="sourceLine" id="cb192-2" data-line-number="2">endt_of_<span class="dv">2016</span> &lt;-<span class="st"> </span><span class="kw">as.Date</span>(<span class="st">&quot;2016-12-31&quot;</span>)</a></code></pre></div>
<p>Use <code>filter()</code> with these variables to find the dog licenses that expire during 2016.</p>
</div>
</div>
<div id="how-can-i-calculate-new-values" class="section level2">
<h2><span class="header-section-number">7.5</span> How can I calculate new values?</h2>
<p>So far, you’ve been manipulating the columns that already exist in a dataset, but what if you want to add new ones? The function <code>mutate()</code> handles this kind of operation.</p>
<p>To see how this works let’s start with a logical expression: <code>animal_name == &quot;CHASE&quot;</code>. If you used this with <code>filter()</code>, you would get all the rows back where the license was issued to a dog named <code>CHASE</code>. Let’s say instead of subsetting the data, you want to add a column called <code>called_chase</code> that contained the <code>TRUE</code> and <code>FALSE</code> result. You might do this for example, if you are interested in comparing the two groups of dogs, rather than just keeping one of them. With <code>mutate()</code> after passing in the data, you pass named arguments, where the name is the name you desire for the new column, and its value is the way to calculate it:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb193-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">called_chase =</span> animal_name <span class="op">==</span><span class="st"> &quot;CHASE&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb193-3" data-line-number="3"><span class="st">  </span><span class="kw">select</span>(animal_name, called_chase)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 2
##    animal_name called_chase
##    &lt;chr&gt;       &lt;lgl&gt;       
##  1 BONITA      FALSE       
##  2 ROCKY       FALSE       
##  3 BULLY       FALSE       
##  4 COCO        FALSE       
##  5 SKI         FALSE       
##  6 CHASE       TRUE        
##  7 CHEWY       FALSE       
##  8 CHASE       TRUE        
##  9 MILEY       FALSE       
## 10 KENZI       FALSE       
## # … with 118,532 more rows</code></pre>
<blockquote>
<p>Take <code>dog_licences</code>, <strong>and then</strong>,
mutate to add a column called <code>called_chase</code> which is the result of testing whether <code>animal_name</code> is exactly <code>&quot;CHASE&quot;</code>, <strong>and then</strong>,
select the columns <code>animal_name</code> and <code>called_chase</code>.</p>
</blockquote>
<p>The select statement isn’t crucial to the calculation here, but it does help me draw your attention to the columns that were involved in this step.</p>
<p>This can be a useful intermediate step in filtering, since it gives you a chance to examine the logical statement before using it to filter:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb195-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">called_chase =</span> animal_name <span class="op">==</span><span class="st"> &quot;CHASE&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb195-3" data-line-number="3"><span class="st">  </span><span class="kw">filter</span>(called_chase)</a></code></pre></div>
<pre><code>## # A tibble: 126 x 16
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1        872 CHASE       M             2013-11-01 00:00:00 Shih Tzu  
##  2        875 CHASE       M             2008-08-01 00:00:00 Labrador …
##  3      32652 CHASE       M             2013-09-01 00:00:00 Yorkshire…
##  4      42125 CHASE       M             2015-08-01 00:00:00 Chihuahua 
##  5     109847 CHASE       M             2013-04-01 00:00:00 Terrier m…
##  6     114557 CHASE       M             2009-07-01 00:00:00 Siberian …
##  7      33434 CHASE       M             2014-08-01 00:00:00 Schnauzer…
##  8      45142 CHASE       M             2005-01-01 00:00:00 Unknown   
##  9       2528 CHASE       M             2011-10-01 00:00:00 Lhasa Apso
## 10       3426 CHASE       M             2014-03-01 00:00:00 Yorkshire…
## # … with 116 more rows, and 11 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;,
## #   called_chase &lt;lgl&gt;</code></pre>
<p>Take a closer look at the argument to mutate:</p>
<pre><code>called_chase = animal_name == &quot;CHASE&quot;</code></pre>
<p>On the left of the <code>=</code> is the argument name, <code>called_chase</code>. This is a name you choose - it should be descriptive and follow good style. On the right of the <code>=</code> is an expression that must either return as many values as there are rows, or a single value. Here, the logical expression involves the column <code>animal_name</code> so it returns as many values as there are rows.</p>
<p>If you would prefer the values to be something other than <code>TRUE</code> or <code>FALSE</code>, instead maybe you want them to be something like <code>&quot;called chase&quot;</code> or <code>&quot;not called chase&quot;</code>, we would need to use the <code>ifelse()</code>.</p>
<p>A call to <code>ifelse()</code> takes the form:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" data-line-number="1"><span class="kw">ifelse</span>(test, yes, no)</a></code></pre></div>
<p>Where <code>test</code> is a logical expression, <code>yes</code> the value for the elements that return <code>TRUE</code>, and <code>no</code> the value for the elements that return <code>FALSE</code>. (Both <code>yes</code> and <code>no</code> could be other column names, in which case, the corresponding element of <code>yes</code> would be returned for <code>TRUE</code> elements).</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb199-3" data-line-number="3">    <span class="dt">called_chase =</span> <span class="kw">ifelse</span>(animal_name <span class="op">==</span><span class="st"> &quot;CHASE&quot;</span>, <span class="st">&quot;called chase&quot;</span>, <span class="st">&quot;not called chase&quot;</span>)</a>
<a class="sourceLine" id="cb199-4" data-line-number="4">    ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-5" data-line-number="5"><span class="st">  </span><span class="kw">select</span>(animal_name, called_chase)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 2
##    animal_name called_chase    
##    &lt;chr&gt;       &lt;chr&gt;           
##  1 BONITA      not called chase
##  2 ROCKY       not called chase
##  3 BULLY       not called chase
##  4 COCO        not called chase
##  5 SKI         not called chase
##  6 CHASE       called chase    
##  7 CHEWY       not called chase
##  8 CHASE       called chase    
##  9 MILEY       not called chase
## 10 KENZI       not called chase
## # … with 118,532 more rows</code></pre>
<p>FIXME: add diagram showing how ifelse works</p>
<p>You can perform multiple mutate steps at once by passing more arguments to <code>mutate()</code>, so an alternative way of writing the above code (with more keystrokes, but with lines that are shorter) would be:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb201-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb201-3" data-line-number="3">    <span class="dt">is_chase =</span> animal_name <span class="op">==</span><span class="st"> &quot;CHASE&quot;</span>,</a>
<a class="sourceLine" id="cb201-4" data-line-number="4">    <span class="dt">called_chase =</span> <span class="kw">ifelse</span>(is_chase, <span class="st">&quot;called chase&quot;</span>, <span class="st">&quot;not called chase&quot;</span>)</a>
<a class="sourceLine" id="cb201-5" data-line-number="5">    ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb201-6" data-line-number="6"><span class="st">  </span><span class="kw">select</span>(animal_name, is_chase, called_chase)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 3
##    animal_name is_chase called_chase    
##    &lt;chr&gt;       &lt;lgl&gt;    &lt;chr&gt;           
##  1 BONITA      FALSE    not called chase
##  2 ROCKY       FALSE    not called chase
##  3 BULLY       FALSE    not called chase
##  4 COCO        FALSE    not called chase
##  5 SKI         FALSE    not called chase
##  6 CHASE       TRUE     called chase    
##  7 CHEWY       FALSE    not called chase
##  8 CHASE       TRUE     called chase    
##  9 MILEY       FALSE    not called chase
## 10 KENZI       FALSE    not called chase
## # … with 118,532 more rows</code></pre>
<p>Notice that the computation for the <code>called_chase</code> column refers to the <code>is_chase</code> column. The arguments to mutate are computed in order, so columns created later in the same <code>mutate()</code> can refer to columns created earlier.</p>
<p>Arithmetic is another common operation that returns as many elements as there are rows. For instance we could see how long licenses are issued for:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb203-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb203-3" data-line-number="3"><span class="st">  </span><span class="kw">select</span>(license_duration)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 1
##    license_duration
##    &lt;drtn&gt;          
##  1 1118 days       
##  2 1826 days       
##  3  697 days       
##  4 1096 days       
##  5 1826 days       
##  6  731 days       
##  7  731 days       
##  8 1097 days       
##  9  421 days       
## 10  402 days       
## # … with 118,532 more rows</code></pre>
<p>The output shows us licenses aren’t issued for a standard time period. In these first rows, there are some licenses issued for a whole number of years: 2 (731 days), 3 (1097 days) and 5 (1826 days). However, others seem to be for fractions of years like 421 days.</p>
<p>FIXME: provide link to RStudio data mini cheatsheet with other functions that are useful with mutate.</p>
<p>You can use <code>mutate()</code> with operations that give one number based on all the rows:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb205-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb205-3" data-line-number="3">    <span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date,</a>
<a class="sourceLine" id="cb205-4" data-line-number="4">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb205-5" data-line-number="5"><span class="st">  </span><span class="kw">select</span>(license_duration, avg_duration)</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 2
##    license_duration avg_duration
##    &lt;drtn&gt;           &lt;drtn&gt;      
##  1 1118 days        467.321 days
##  2 1826 days        467.321 days
##  3  697 days        467.321 days
##  4 1096 days        467.321 days
##  5 1826 days        467.321 days
##  6  731 days        467.321 days
##  7  731 days        467.321 days
##  8 1097 days        467.321 days
##  9  421 days        467.321 days
## 10  402 days        467.321 days
## # … with 118,532 more rows</code></pre>
<p>You’ll get back the original number of rows, but the single value will be repeated in all of them - on average licenses are issued for 467.321 days. You’ll see a different verb, <code>summarise()</code> that collapses many rows into one later in this chapter.</p>
<div id="exercise-ages-of-dogs" class="section level3">
<h3><span class="header-section-number">7.5.1</span> Exercise: Ages of dogs</h3>
<p>Use <code>mutate()</code> to add a column <code>age_at_issue</code> that contains the dogs approximate age on the day the license was issued.</p>
</div>
<div id="exercise-unknown-breeds" class="section level3">
<h3><span class="header-section-number">7.5.2</span> Exercise: Unknown breeds</h3>
<p>Use <code>mutate()</code> along with <code>ifelse()</code> to create a column <code>breed</code> that takes values <code>&quot;unknown&quot;</code> if <code>breed_name</code> is <code>&quot;unknown&quot;</code> and <code>&quot;known&quot;</code> otherwise.</p>
<p><em>Extra challenge</em> Can you figure out if the licenses issued to unknown breed dogs are of longer or shorter duration on average than known breed dogs?</p>
</div>
<div id="exercise-name-length" class="section level3">
<h3><span class="header-section-number">7.5.3</span> Exercise: Name length</h3>
<p>The function <code>str_length()</code> in the stringr package finds the length of character strings. Replace the <code>___</code> in following code to add a column called <code>name_length</code> that contains the length of the dog’s name:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb207-2" data-line-number="2"><span class="st">  </span><span class="kw">___</span>(<span class="dt">___ =</span> stringr<span class="op">::</span><span class="kw">str_length</span>(animal_name))</a></code></pre></div>
<p>Now add an <code>arrange()</code> step to find the licenses issued to dogs with the longest names?</p>
</div>
</div>
<div id="how-can-i-tell-whats-gone-wrong-in-my-programs" class="section level2">
<h2><span class="header-section-number">7.6</span> How can I tell what’s gone wrong in my programs?</h2>
<p>FIXME: The errors shown in the markdown are way more informative than those in the Console. Try to get the error displaying in the book like they do for someone in the console?</p>
<p>Let me share an interaction my (CVW’s) husband had at a Trader Joes (a small specialized supermarket) soon after we arrived in the USA from New Zealand.</p>
<p>Josh: “Do you sell <em>bat-trees</em>?”</p>
<p>Store-person: “What?”</p>
<p>Josh: “Do you sell <em>bat-trees</em>?”</p>
<p>Store person: “Huh? <em>Bat…trees</em>?”</p>
<p>Josh: &quot;Do you sell <em>bat-er-ries</em>?</p>
<p>Store-person: “Oh…you mean batteries! No. We don’t sell batteries.”</p>
<p>This is a pretty accurate analogy for what it feels like when you are learning R. You know what you want, but you have to ask for it in a way R understands. When R doesn’t understand you, or when R can’t give you what you want, you’ll get an error. You’ll know when you get one in R because the only output you see will start with <code>Error</code>.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" data-line-number="1"><span class="kw">buy_batteries</span>(<span class="dt">store =</span> <span class="st">&quot;Trader Joes&quot;</span>)</a></code></pre></div>
<pre><code>## Error in buy_batteries(store = &quot;Trader Joes&quot;): could not find function &quot;buy_batteries&quot;</code></pre>
<p>It’s also a good illustration of the two kinds of problems that occur: syntax errors and runtime errors. Syntax errors are like the “What? Huh?” moments. R doesn’t understand what you are asking it to do, because something about the way you are asking doesn’t conform to what R expects and it will not even try to run your code. Runtime errors are more like the “No, I can’t help you” moments. R understands what you are asking and runs your code, but during the run something goes wrong and R has to stop running the code.</p>
<p>You generally want to make sure you’ve ruled out syntax errors before assuming it’s a runtime error. Unfortunately, R doesn’t distinguish these two types of error in its output, so we’ll discuss some of the most common examples in the following sections.</p>
<p>This analogy is also a reminder that sometimes you’ll have to repeat yourself. With R, giving the exact same instruction should always result in the exact same error, but it’s not uncommon, even for longtime R users, to run and edit a line of code multiple times before it runs without error.</p>
<p>There is one flaw in this analogy: R isn’t a real person. So, if you need to vent <em>your</em> frustration by cursing it, insulting its parentage or storming off, it’s fine, no one’s feelings will be hurt. Of course, it won’t change R’s response…</p>
<div id="common-syntax-errors" class="section level3">
<h3><span class="header-section-number">7.6.1</span> Common syntax errors</h3>
<p>Syntax errors occur when your code can’t be broken into its component pieces by R. For example, R expects the arguments to a function to start after the opening parenthesis (<code>(</code>), be separated by a comma (<code>,</code>) and finish at the closing parenthesis (<code>)</code>). When R sees this code:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" data-line-number="1"><span class="kw">filter</span>(dog_licenses breed_name <span class="op">==</span><span class="st"> &quot;Finnish Lapphund&quot;</span>)</a></code></pre></div>
<pre><code>## Error: &lt;text&gt;:1:21: unexpected symbol
## 1: filter(dog_licenses breed_name
##                         ^</code></pre>
<p>The missing comma means R can’t figure out where the first argument to <code>filter()</code> ends: is it after <code>dog_licenses</code>, after <code>breed_name</code>, or after <code>==</code>?</p>
<p>Take a closer look at the error message. Error messages always begin with <code>Error</code>, then optionally the name of the function that returned an error (not in this example), followed by a <code>:</code>, and some description of the error that occurred. The message <code>unexpected symbol</code> is one common kind of syntax error - in this case R encountered some code where it was expecting a comma or closing parenthesis. We can fix it by putting in the missing comma:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" data-line-number="1"><span class="kw">filter</span>(dog_licenses, breed_name <span class="op">==</span><span class="st"> &quot;Finnish Lapphund&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 15
##   row_number animal_name animal_gender animal_birth_month  breed_name
##        &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
## 1     118408 FREDDIE     M             2011-11-01 00:00:00 Finnish L…
## # … with 10 more variables: borough &lt;chr&gt;, zip_code &lt;dbl&gt;,
## #   community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
<p>Syntax errors are usually the result of typos. Some things to keep an eye out for:</p>
<ul>
<li><p>If you are modelling your code on an example, pay very close attention to the punctuation: commas <code>,</code>, parenthesis <code>(</code>, <code>)</code>, brackets, <code>[</code>, <code>]</code>, and quotes <code>&quot;</code>, <code>'</code>. Every opening parenthesis, bracket, or quote needs a matching closing one, and they must be closed in the reverse order they were opened.</p></li>
<li><p>New lines don’t matter if they happen between arguments, or after pipe operators, but they can be problematic in other locations.</p></li>
<li><p>R ignores other whitespace (spaces or tabs) unless it’s inside a character string (i.e. inside quotes), so different spacing shouldn’t be the cause of an error, but it is a good idea to follow good style for spacing. FIXME: link to style guide section.</p></li>
</ul>
</div>
<div id="exercise-syntax-errors" class="section level3">
<h3><span class="header-section-number">7.6.2</span> Exercise: Syntax errors</h3>
<p>Fix these <strong>syntax</strong> errors.</p>
<ul>
<li><div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb214-2" data-line-number="2"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(license_expired_date))<span class="er">)</span></a></code></pre></div>
<pre><code>## Error: &lt;text&gt;:2:38: unexpected &#39;)&#39;
## 1: dog_licenses %&gt;%
## 2:   arrange(desc(license_expired_date)))
##                                         ^</code></pre></li>
<li><div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb216-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb216-3" data-line-number="3">    <span class="dt">month_born =</span> lubridate<span class="op">::</span><span class="kw">month</span>(animal_birth_month)</a>
<a class="sourceLine" id="cb216-4" data-line-number="4">    <span class="dt">year_born =</span> lubridate<span class="op">::</span><span class="kw">year</span>(animal_birth_month))</a></code></pre></div>
<pre><code>## Error: &lt;text&gt;:4:5: unexpected symbol
## 3:     month_born = lubridate::month(animal_birth_month)
## 4:     year_born
##        ^</code></pre></li>
<li><div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb218-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(animal_name <span class="op">==</span><span class="st"> &quot;BRUNO)</span></a></code></pre></div>
<pre><code>## Error: &lt;text&gt;:2:25: unexpected INCOMPLETE_STRING
## 1: dog_licenses %&gt;%
## 2:   filter(animal_name == &quot;BRUNO)
##                            ^</code></pre>
<p>(If you run this code in the Console, you might not get an error, but you should see a <code>+</code> on a new line, a signal that R is waiting for more input and a clue that there is something missing in this code).</p></li>
<li><div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" data-line-number="1">dog_licenses</a>
<a class="sourceLine" id="cb220-2" data-line-number="2">  <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(animal_gender <span class="op">==</span><span class="st"> &quot;M&quot;</span>)</a></code></pre></div>
<pre><code>## Error: &lt;text&gt;:2:3: unexpected SPECIAL
## 1: dog_licenses
## 2:   %&gt;%
##      ^</code></pre></li>
</ul>
</div>
<div id="common-runtime-errors" class="section level3">
<h3><span class="header-section-number">7.6.3</span> Common runtime errors</h3>
<p>Runtime errors come in an infinite number of flavors because there are so many ways that you ask for that might be impossible to do. For example you might try to do arithmetic with character strings:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" data-line-number="1"><span class="st">&quot;apple&quot;</span> <span class="op">+</span><span class="st"> &quot;banana&quot;</span></a></code></pre></div>
<pre><code>## Error in &quot;apple&quot; + &quot;banana&quot;: non-numeric argument to binary operator</code></pre>
<p>Or try to filter with something that isn’t a logical:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(animal_name)</a></code></pre></div>
<pre><code>## Error: Argument 2 filter condition does not evaluate to a logical vector</code></pre>
<p>Perhaps the most common runtime error is of the form <code>Error: object not found</code>:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1">an_object_i_dont_have</a></code></pre></div>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;an_object_i_dont_have&#39; not found</code></pre>
<p>This is R complaining that you’ve asked it to operate on an object that it doesn’t know about. Often this is actually a typo in disguise, for example you’ve misspelled the name of the object,</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1">my_object &lt;-<span class="st"> </span><span class="dv">12</span></a>
<a class="sourceLine" id="cb228-2" data-line-number="2">my_objet</a></code></pre></div>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;my_objet&#39; not found</code></pre>
<p>you’ve used the wrong case,</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1">My_object</a></code></pre></div>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;My_object&#39; not found</code></pre>
<p>or you’ve forgotten that you’ve used a separator</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1">myobject</a></code></pre></div>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;myobject&#39; not found</code></pre>
<p>This error also often arises when you forgot quotes around strings. For example, if we want all the dogs that are male, and try</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(animal_gender <span class="op">==</span><span class="st"> </span>M)</a></code></pre></div>
<pre><code>## Error: object &#39;M&#39; not found</code></pre>
<p>you get an error because R is looking for an object called <code>M</code> to compare to the values in the column called <code>animal_gender</code>. What we really wanted to do was compare the values in <code>animal_gender</code> to the string <code>&quot;M&quot;</code>:</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(animal_gender <span class="op">==</span><span class="st"> &quot;M&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 64,770 x 15
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1        548 ROCKY       M             2014-05-01 00:00:00 Labrador …
##  2        622 BULLY       M             2010-07-01 00:00:00 American …
##  3        633 COCO        M             2005-02-01 00:00:00 Labrador …
##  4        872 CHASE       M             2013-11-01 00:00:00 Shih Tzu  
##  5        874 CHEWY       M             2014-09-01 00:00:00 Shih Tzu  
##  6        875 CHASE       M             2008-08-01 00:00:00 Labrador …
##  7        976 APOLLO      M             2014-10-01 00:00:00 American …
##  8       1297 JERRY       M             2009-06-01 00:00:00 Labrador …
##  9       2133 SIMON       M             2010-12-01 00:00:00 Havanese  
## 10       2289 BUDDY       M             2012-06-01 00:00:00 Labrador …
## # … with 64,760 more rows, and 10 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;</code></pre>
</div>
<div id="exercise-object-not-found" class="section level3">
<h3><span class="header-section-number">7.6.4</span> Exercise: <code>object not found</code></h3>
<p>Fix these <code>object not found</code> errors. (Hint: the names of the objects or variables being created should give you a clue to the intent of the code)</p>
<ul>
<li><div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb238-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year_issued =</span> lubridate<span class="op">::</span><span class="kw">year</span>(Liscenceissuedate))</a></code></pre></div>
<pre><code>## Error in lubridate::year(Liscenceissuedate): object &#39;Liscenceissuedate&#39; not found</code></pre></li>
<li><div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1">dogs_named_bruno &lt;-<span class="st"> </span>dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb240-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(animal_name <span class="op">==</span><span class="st"> </span>BRUNO)</a></code></pre></div>
<pre><code>## Error: object &#39;BRUNO&#39; not found</code></pre></li>
</ul>
</div>
<div id="warnings-and-messages" class="section level3">
<h3><span class="header-section-number">7.6.5</span> Warnings and messages</h3>
<p>There are two other kinds of alerts R can give: warnings and messages. These can both appear in the console with the same color as an error, but they are informational as opposed to fatal.</p>
<p>Messages are purely informational, for example when you read data in with <code>read_csv()</code> you get a message that describes the columns and their data types as parsed by the function:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1">sites &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;site.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   site_id = col_character(),
##   latitude = col_double(),
##   longitude = col_double()
## )</code></pre>
<p>Warnings generally alert you that something was slightly unexpected but that R recovered and gave you a result anyway. Poorly formatted CSV files will often result in warnings from <code>read_csv()</code>:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1">bad_csv &lt;-<span class="st"> &quot;</span></a>
<a class="sourceLine" id="cb244-2" data-line-number="2"><span class="st">id,</span></a>
<a class="sourceLine" id="cb244-3" data-line-number="3"><span class="st">1, 2</span></a>
<a class="sourceLine" id="cb244-4" data-line-number="4"><span class="st">2, 1</span></a>
<a class="sourceLine" id="cb244-5" data-line-number="5"><span class="st">3, 5</span></a>
<a class="sourceLine" id="cb244-6" data-line-number="6"><span class="st">&quot;</span></a>
<a class="sourceLine" id="cb244-7" data-line-number="7">bad &lt;-<span class="st"> </span><span class="kw">read_csv</span>(bad_csv)</a></code></pre></div>
<pre><code>## Warning: Missing column names filled in: &#39;X2&#39; [2]</code></pre>
<p>Here there was a missing column name. <code>read_csv()</code> still returns an object but the warning alerts you that it made some assumption to get it, i.e. that it made up a column name:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1">bad</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##      id    X2
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     1     2
## 2     2     1
## 3     3     5</code></pre>
<p>Warnings don’t <strong>stop</strong> you from proceeding, but they should alert you to question whether you <strong>should be</strong> proceeding.</p>
</div>
<div id="what-do-i-do-when-i-get-an-error-i-cant-fix" class="section level3">
<h3><span class="header-section-number">7.6.6</span> What do I do when I get an <code>Error</code> I can’t fix?</h3>
<ul>
<li><p>Check that the error is reproducible. Restart R with a clean slate and re-run your code up to and including the code that gives the error. This is the R version of the classic tech advice to “turn it off, then turn it on again”. FIXME: link to reproducibility chapter.</p></li>
<li><p>Try searching for it online: for example, searching for “R unexpected string constant” lead me to the question <a href="https://stackoverflow.com/questions/25889234/error-unexpected-symbol-input-string-constant-numeric-constant-special-in-my-co">“Error: unexpected symbol/input/string constant/numeric constant/SPECIAL in my code” on StackOverflow</a> which gives some great examples of ways this error might arise.</p></li>
<li><p>Ask for help. You are most likely to get help when you can provide a reproducible example. Stack Overflow
has detailed instruction on how to create a <a href="https://stackoverflow.com/help/minimal-reproducible-example">minimal reproducible
example</a> when asking a question to increase the chances that the
question receives a specific and helpful answer. The key principles listed on
the website recommends that an answer follows these guidelines:</p>
<blockquote>
<ul>
<li>Minimal – Use as little code as possible that still produces the same
problem</li>
<li>Complete – Provide all parts someone else needs to reproduce your problem
in the question itself</li>
<li>Reproducible – Test the code you’re about to provide to make sure it
reproduces the problem</li>
</ul>
</blockquote></li>
</ul>
</div>
</div>
<div id="how-can-i-operate-on-subsets-of-my-data" class="section level2">
<h2><span class="header-section-number">7.7</span> How can I operate on subsets of my data?</h2>
<p>The syntax for <code>summarise()</code> is the same as <code>mutate()</code> but it expects operations that reduce all rows down to one row. Recall from <code>mutate()</code> that this code added the average license duration to every row of the data:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration))</a></code></pre></div>
<p>You actually saw this in one <code>mutate()</code> statement, but I’ve separated out the line that calculates the average so it’s easier to see the difference with <code>summarise()</code>. See what happens when you switch out the final <code>mutate()</code> with <code>summarise()</code>:</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb249-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb249-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb249-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   avg_duration
##   &lt;drtn&gt;      
## 1 467.321 days</code></pre>
<p>Instead of the the one value repeated on every row, we get a new tibble with only one row, and a single column that corresponds to our requested summary.</p>
<p>Any function that takes many values and reduces them to one is a good candidate for <code>summarise()</code>, for example we could find the shortest licence duration by swapping in <code>min()</code> instead of <code>mean()</code>:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb251-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb251-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   shortest_duration
##   &lt;drtn&gt;           
## 1 1 days</code></pre>
<p>Like <code>mutate()</code> you can also create multiple summary columns at once:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb253-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb253-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb253-4" data-line-number="4">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb253-5" data-line-number="5">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb253-6" data-line-number="6">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration)</a>
<a class="sourceLine" id="cb253-7" data-line-number="7">  )</a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   avg_duration shortest_duration longest_duration
##   &lt;drtn&gt;       &lt;drtn&gt;            &lt;drtn&gt;          
## 1 467.321 days 1 days            2191 days</code></pre>
<p>FIXME: link to cheatsheet with list of other useful functions.</p>
<p>Lot’s of statistical operations produce one numbers summaries and are appropriate for use with <code>summarise()</code>: <code>sd()</code>, <code>min()</code>, <code>max()</code>, <code>mean()</code>, <code>median()</code>, <code>quantile()</code> (with a single argument). Whenever you are summarizing many rows, it’s a good idea to keep track of how many rows were summarized. This is so common, dplyr provides a special function, <code>n()</code>, that simply counts the number of rows. To add it to your summary:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb255-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb255-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb255-4" data-line-number="4">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb255-5" data-line-number="5">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb255-6" data-line-number="6">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb255-7" data-line-number="7">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb255-8" data-line-number="8">  )</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   avg_duration shortest_duration longest_duration n_licenses
##   &lt;drtn&gt;       &lt;drtn&gt;            &lt;drtn&gt;                &lt;int&gt;
## 1 467.321 days 1 days            2191 days            118542</code></pre>
<p>Now, imagine you want this summary just for licenses issued to dogs in the Bronx. You might do something like:</p>
<blockquote>
<p>Take the <code>dog_licenses</code> data, <strong>and then</strong>,
mutate to add a column called <code>license_duration</code>, <strong>and then</strong>
filter to keep rows where the <code>borough</code> is <code>&quot;Bronx&quot;</code>, <strong>and then</strong>
summarise to find the mean, min and max duration along with the number of rows.</p>
</blockquote>
<p>In code:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-3" data-line-number="3"><span class="st">  </span><span class="kw">filter</span>(borough <span class="op">==</span><span class="st"> &quot;Bronx&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb257-5" data-line-number="5">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb257-6" data-line-number="6">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb257-7" data-line-number="7">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb257-8" data-line-number="8">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb257-9" data-line-number="9">  )</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   avg_duration  shortest_duration longest_duration n_licenses
##   &lt;drtn&gt;        &lt;drtn&gt;            &lt;drtn&gt;                &lt;int&gt;
## 1 435.9884 days 2 days            1919 days             12043</code></pre>
<p>But how does this compare to Brooklyn? You could do the same operation again, but now for Brooklyn:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb259-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb259-3" data-line-number="3"><span class="st">  </span><span class="kw">filter</span>(borough <span class="op">==</span><span class="st"> &quot;Brooklyn&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb259-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb259-5" data-line-number="5">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb259-6" data-line-number="6">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb259-7" data-line-number="7">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb259-8" data-line-number="8">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb259-9" data-line-number="9">  )</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   avg_duration  shortest_duration longest_duration n_licenses
##   &lt;drtn&gt;        &lt;drtn&gt;            &lt;drtn&gt;                &lt;int&gt;
## 1 465.8845 days 2 days            2191 days             29334</code></pre>
<p>What about Queens? This kind of operation—summarising different subsets of the same data—is so common there is a much easier way to do it: combining <code>summarise()</code> with <code>group_by()</code>.</p>
<p>The only difference in the code, is that instead of filtering for a specific <code>borough</code> we’ll <code>group_by()</code> the column <code>borough</code>.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb261-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb261-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb261-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(borough) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb261-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb261-5" data-line-number="5">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb261-6" data-line-number="6">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb261-7" data-line-number="7">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb261-8" data-line-number="8">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb261-9" data-line-number="9">  )</a></code></pre></div>
<pre><code>## # A tibble: 57 x 5
##    borough      avg_duration  shortest_duration longest_duration n_licenses
##    &lt;chr&gt;        &lt;drtn&gt;        &lt;drtn&gt;            &lt;drtn&gt;                &lt;int&gt;
##  1 ARVERNE      334.0000 days 334 days           334 days                 1
##  2 Astoria      498.0000 days 239 days           757 days                 2
##  3 ASTORIA      387.6667 days 366 days           405 days                 3
##  4 B            347.0000 days 347 days           347 days                 1
##  5 Bayside      410.0000 days 410 days           410 days                 1
##  6 BELLE HARBOR 309.0000 days 309 days           309 days                 1
##  7 Briarwood    540.5000 days 358 days           723 days                 2
##  8 Bronx        435.9884 days   2 days          1919 days             12043
##  9 BRONX        370.3333 days  72 days           418 days               102
## 10 Brooklyn     465.8845 days   2 days          2191 days             29334
## # … with 47 more rows</code></pre>
<p>The <code>group_by()</code> verb doesn’t perform any changes to the data except to add a signal that this data is now grouped. Subsequent operations will then happen within these groups. In the case of <code>summarise()</code> we now get one row per group, and these are all stacked together in our result.</p>
<p>You might have been a little surprised by the result above. I thought there were only five boroughs in New York (at least that’s what the Beastie Boys told me). Notice some boroughs are represented more than once by variations in case or spelling: <code>Bronx</code>, <code>BRONX</code>. As far as <code>group_by()</code> is concerned these are distinct values of this variable. There also seem to be smaller designations than Borough in this data. You’ll get a chance to try and resolve this in an exercise below.</p>
<div id="exercise-dog-birth-months" class="section level3">
<h3><span class="header-section-number">7.7.1</span> Exercise: Dog birth months</h3>
<p>The following code creates a new column <code>month_born</code> that holds the name of the month the licensed dog was born:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb263-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">month_born =</span> lubridate<span class="op">::</span><span class="kw">month</span>(animal_birth_month, <span class="dt">label =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<p>Use a <code>group_by()</code> step and a <code>summarise()</code> step to find the number of dogs born in each month. Which month stands out? Can you guess why?</p>
</div>
<div id="exercise-order-matters" class="section level3">
<h3><span class="header-section-number">7.7.2</span> Exercise: Order matters?</h3>
<p>In the example above for dogs licensed in Brooklyn:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb264-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb264-3" data-line-number="3"><span class="st">  </span><span class="kw">filter</span>(borough <span class="op">==</span><span class="st"> &quot;Brooklyn&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb264-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb264-5" data-line-number="5">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb264-6" data-line-number="6">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb264-7" data-line-number="7">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb264-8" data-line-number="8">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb264-9" data-line-number="9">  )</a></code></pre></div>
<p>the <code>filter()</code> step came after the <code>mutate()</code> step. Does this matter?</p>
<ul>
<li><p>Swap the order in the code and see if you get the same results.</p></li>
<li><p>Write out how you might describe the steps. Is it obvious you can swap the filter and mutate step and get the same results?</p></li>
<li><p>Which steps can’t you swap the order of? Why?</p></li>
<li><p><em>Despite giving the same results, some orderings of the data manipulation steps will take longer to compute. Can you guess why?</em></p></li>
</ul>
</div>
<div id="exercise-the-five-boroughs" class="section level3">
<h3><span class="header-section-number">7.7.3</span> Exercise: the five boroughs</h3>
<p>The column <code>neighborhood_tabulation_area</code> is a code for the “Neighborhood Tabulation Areas”, and has been geo-coded from the licensee’s address (as opposed to self reported). The first two characters correspond to the Borough.</p>
<p>This code creates a new variable called <code>borough_code</code> that contains just these two characters:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">borough_code =</span> stringr<span class="op">::</span><span class="kw">str_sub</span>(neighborhood_tabulation_area, <span class="dv">1</span>, <span class="dv">2</span>))</a></code></pre></div>
<pre><code>## # A tibble: 118,542 x 16
##    row_number animal_name animal_gender animal_birth_month  breed_name
##         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dttm&gt;              &lt;chr&gt;     
##  1        533 BONITA      F             2013-05-01 00:00:00 Unknown   
##  2        548 ROCKY       M             2014-05-01 00:00:00 Labrador …
##  3        622 BULLY       M             2010-07-01 00:00:00 American …
##  4        633 COCO        M             2005-02-01 00:00:00 Labrador …
##  5        655 SKI         F             2012-09-01 00:00:00 American …
##  6        872 CHASE       M             2013-11-01 00:00:00 Shih Tzu  
##  7        874 CHEWY       M             2014-09-01 00:00:00 Shih Tzu  
##  8        875 CHASE       M             2008-08-01 00:00:00 Labrador …
##  9        893 MILEY       F             2008-07-01 00:00:00 Boxer     
## 10        919 KENZI       F             2010-05-01 00:00:00 Schnauzer…
## # … with 118,532 more rows, and 11 more variables: borough &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, community_district &lt;dbl&gt;, census_tract_2010 &lt;dbl&gt;,
## #   neighborhood_tabulation_area &lt;chr&gt;, city_council_district &lt;dbl&gt;,
## #   congressional_district &lt;dbl&gt;, state_senatorial_district &lt;dbl&gt;,
## #   license_issued_date &lt;date&gt;, license_expired_date &lt;date&gt;,
## #   borough_code &lt;chr&gt;</code></pre>
<p>Which borough has the longest average licence duration?</p>
</div>
</div>
<div id="how-can-i-read-my-own-tabular-data-into-r" class="section level2">
<h2><span class="header-section-number">7.8</span> How can I read my own tabular data into R?</h2>
<div id="what-is-tabular-data" class="section level3">
<h3><span class="header-section-number">7.8.1</span> What is tabular data?</h3>
<p>Tabular data describes data that is in the form of a table: values arranged in rows each of the same length, or equivalently values arranged in columns each of the same length. Here’s a small example of some tabular data:</p>
<table>
<thead>
<tr class="header">
<th align="left">site_id</th>
<th align="right">latitude</th>
<th align="right">longitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DR-1</td>
<td align="right">-49.85</td>
<td align="right">-128.57</td>
</tr>
<tr class="even">
<td align="left">DR-3</td>
<td align="right">-47.15</td>
<td align="right">-126.72</td>
</tr>
<tr class="odd">
<td align="left">MSK-4</td>
<td align="right">-48.87</td>
<td align="right">-123.40</td>
</tr>
</tbody>
</table>
<p>Each row records information on a site at which water measurements are taken. There are three columns: a site identification code, and the location of the site in latitude and longitude.</p>
<p>This is an incredibly common way of <em>displaying</em> data, but when <em>storing</em> tabular data in a file, we need a way to communicate when records and values begin and end. A very popular format for doing this is CSV. CSV, is short for <strong>c</strong>omma <strong>s</strong>eparated <strong>v</strong>alues, and like the name suggests, a comma, <code>,</code>, is used to separate the values for each column, while each record goes on a new line. The file is plain text, but we use the extension <code>.csv</code> to indicate that is follows the CSV format conventions.</p>
<p>Here’s how the table above would look inside the CSV file <code>site.csv</code>:</p>
<pre><code>site_id,latitude,longitude
DR-1,-49.85,-128.57
DR-3,-47.15,-126.72
MSK-4,-48.87,-123.4</code></pre>
<p>In this case the first line has the column names, this is common (and recommended!), but not universal.</p>
<p>Why is CSV so popular?</p>
<ul>
<li>It’s human readable. CSV isn’t a special file type, it is a simple plain text file that follows some conventions. This means you don’t need any special software to look at the contents—you can open it up in anything that can examine text and take a look inside.</li>
<li>It’s computer readable. Because CSV files all have the same structure it’s easy to write computer programs to read them. This means in almost any program designed to work with data, which is basically all the common programming languages, you’ll find functions that will import CSV files. This also means it’s easy to create CSV files—you can export them from Excel, write them from R, or even write one from scratch in a text editor.</li>
</ul>
<p>If you want to look inside a CSV file in RStudio you can navigate to its location in the “Files” pane and click on its name. Selecting “View File”, will open it in the Source pane.</p>
<p>However, if you want to work with CSV data in R, it isn’t enough to look inside the file. You need to read the contents of the file and store it in R’s memory. This process is known as data import.</p>
</div>
<div id="importing-csv-data-into-r" class="section level3">
<h3><span class="header-section-number">7.8.2</span> Importing CSV data into R</h3>
<p>To work with data in R you need to have it in R’s memory. The <code>read_csv()</code> function in the readr package will import a CSV file, and represent it as a tibble, if you give it the location of the CSV file. For example, to read the <code>site.csv</code> data and store it in an object called <code>sites</code>:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb268-2" data-line-number="2">sites &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="kw">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;site.csv&quot;</span>))</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   site_id = col_character(),
##   latitude = col_double(),
##   longitude = col_double()
## )</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" data-line-number="1">sites</a></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   site_id latitude longitude
##   &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1 DR-1       -49.8     -129.
## 2 DR-3       -47.2     -127.
## 3 MSK-4      -48.9     -123.</code></pre>
<p>FIXME: talk about files paths, point reader to the place where file paths are talked about, or assume file is in their working directory.</p>
<p>Notice that <code>read_csv()</code> gave us a message about what it did: it parsed our data file and found three columns <code>site_id</code>, <code>latitude</code> and <code>longitude</code>. It also mentions what kind of data it assumed was in each column. FIXME: point to further discussion of data types.</p>
<p>The object <code>sites</code> is now R’s representation of the data from the <code>site.csv</code> file.</p>
</div>
<div id="exercise-import-visited.csv" class="section level3">
<h3><span class="header-section-number">7.8.3</span> Exercise: Import <code>visited.csv</code></h3>
<p>Use <code>read_csv()</code> to read <code>visited.csv</code> into R. How does R indicate a cell with a missing value?</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" data-line-number="1">visited &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="kw">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;visited.csv&quot;</span>))</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   visit_id = col_double(),
##   site_id = col_character(),
##   visit_date = col_date(format = &quot;&quot;)
## )</code></pre>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" data-line-number="1">visited</a></code></pre></div>
<pre><code>## # A tibble: 8 x 3
##   visit_id site_id visit_date
##      &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;    
## 1      619 DR-1    1927-02-08
## 2      622 DR-1    1927-02-10
## 3      734 DR-3    1930-01-07
## 4      735 DR-3    1930-01-12
## 5      751 DR-3    1930-02-26
## 6      752 DR-3    NA        
## 7      837 MSK-4   1932-01-14
## 8      844 DR-1    1932-03-22</code></pre>
</div>
<div id="exercise-import-irs-tax-return-data-for-new-york-city" class="section level3">
<h3><span class="header-section-number">7.8.4</span> Exercise: Import IRS tax return data for New York City</h3>
<p>Use <code>read_csv()</code> to import the CSV file <code>nyc-tax-returns.csv</code>.</p>
<p>FIXME: Should we introduce the “common things that go wrong” / “the most common additional arguments”, e.g. <code>skip</code>, <code>na</code>, <code>col_names</code>, <code>col_types</code>? My feeling is not now, but sometime later.</p>
</div>
</div>
<div id="how-can-i-save-my-results" class="section level2">
<h2><span class="header-section-number">7.9</span> How can I save my results?</h2>
<p>Say, you’ve now got a summary of the license durations by borough:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb276-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb276-3" data-line-number="3">    <span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date,</a>
<a class="sourceLine" id="cb276-4" data-line-number="4">    <span class="dt">borough_code =</span> stringr<span class="op">::</span><span class="kw">str_sub</span>(neighborhood_tabulation_area, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb276-5" data-line-number="5"><span class="st">  </span><span class="kw">group_by</span>(borough_code) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb276-6" data-line-number="6"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb276-7" data-line-number="7">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb276-8" data-line-number="8">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb276-9" data-line-number="9">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb276-10" data-line-number="10">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb276-11" data-line-number="11">  )</a></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##   borough_code avg_duration  shortest_duration longest_duration n_licenses
##   &lt;chr&gt;        &lt;drtn&gt;        &lt;drtn&gt;            &lt;drtn&gt;                &lt;int&gt;
## 1 BK           465.2768 days 2 days            2191 days             29558
## 2 BX           435.8062 days 2 days            1919 days             12050
## 3 MN           494.0276 days 1 days            2189 days             41668
## 4 QN           452.1386 days 2 days            2186 days             24420
## 5 SI           439.4875 days 4 days            2164 days             10846</code></pre>
<p>How do you save this result for future use?</p>
<p>If you just need this tibble later in your code you can assign it to a variable:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" data-line-number="1">duration_by_borough &lt;-<span class="st"> </span>dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb278-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb278-3" data-line-number="3">    <span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date,</a>
<a class="sourceLine" id="cb278-4" data-line-number="4">    <span class="dt">borough_code =</span> stringr<span class="op">::</span><span class="kw">str_sub</span>(neighborhood_tabulation_area, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb278-5" data-line-number="5"><span class="st">  </span><span class="kw">group_by</span>(borough_code) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb278-6" data-line-number="6"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb278-7" data-line-number="7">    <span class="dt">avg_duration =</span> <span class="kw">mean</span>(license_duration),</a>
<a class="sourceLine" id="cb278-8" data-line-number="8">    <span class="dt">shortest_duration =</span> <span class="kw">min</span>(license_duration),</a>
<a class="sourceLine" id="cb278-9" data-line-number="9">    <span class="dt">longest_duration =</span> <span class="kw">max</span>(license_duration),</a>
<a class="sourceLine" id="cb278-10" data-line-number="10">    <span class="dt">n_licenses =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb278-11" data-line-number="11">  )</a></code></pre></div>
<p>Then you can access it whenever you need it:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" data-line-number="1">duration_by_borough</a></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##   borough_code avg_duration  shortest_duration longest_duration n_licenses
##   &lt;chr&gt;        &lt;drtn&gt;        &lt;drtn&gt;            &lt;drtn&gt;                &lt;int&gt;
## 1 BK           465.2768 days 2 days            2191 days             29558
## 2 BX           435.8062 days 2 days            1919 days             12050
## 3 MN           494.0276 days 1 days            2189 days             41668
## 4 QN           452.1386 days 2 days            2186 days             24420
## 5 SI           439.4875 days 4 days            2164 days             10846</code></pre>
<p>This keeps our result around in memory, but often you also want to preserve the data in a file on disk. There are two common choices for format: CSV and RDS.</p>
<p>You’ve already seen CSV files. Saving your results in this format gives you all the benefits of that format: plain text files easily shared and opened. You can save a tibble as a CSV file with the readr function <code>write_csv()</code>, where all you need to specify is the path:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" data-line-number="1">duration_by_borough <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">write_csv</span>(<span class="st">&quot;duration-by-borough.csv&quot;</span>)</a></code></pre></div>
<p>You can then read this file in any project or R session with <code>read_csv()</code>:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" data-line-number="1">duration_by_borough &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;duration-by-borough.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   borough_code = col_character(),
##   avg_duration = col_double(),
##   shortest_duration = col_double(),
##   longest_duration = col_double(),
##   n_licenses = col_double()
## )</code></pre>
<p>RDS files are a special R format. They are binary files as opposed to plain text files, which means you can’t just open them up and look inside. If you are sharing them you’d also need your collaborators to have R. These are downsides, but the advantage of this format is that it can be much quicker to load, it will preserve special R data types (for example factors, or nested structures), and can save any R object not just tabular data structures.</p>
<p>To save the tibble as an RDS, use <code>write_rds()</code>:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" data-line-number="1">duration_by_borough <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">write_rds</span>(<span class="st">&quot;duration-by-borough.rds&quot;</span>)</a></code></pre></div>
<p>To read it back in, use <code>read_rds()</code>:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb285-1" data-line-number="1">duration_by_borough &lt;-<span class="st"> </span><span class="kw">read_rds</span>(<span class="st">&quot;duration-by-borough.rds&quot;</span>)</a></code></pre></div>
<p>Often you’ll save your data in both formats to make sure you get the best of both worlds. You’ll talk more about where to save your data in FIXME: add link.</p>
<div id="exercise" class="section level3">
<h3><span class="header-section-number">7.9.1</span> Exercise</h3>
<p>Save the tibble with our extra columns:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" data-line-number="1">dog_licenses <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb286-3" data-line-number="3">    <span class="dt">license_duration =</span> license_expired_date <span class="op">-</span><span class="st"> </span>license_issued_date,</a>
<a class="sourceLine" id="cb286-4" data-line-number="4">    <span class="dt">borough_code =</span> stringr<span class="op">::</span><span class="kw">str_sub</span>(neighborhood_tabulation_area, <span class="dv">1</span>, <span class="dv">2</span>))</a></code></pre></div>
<p>into a CSV file called <code>dog-licenses-extra.csv</code>.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r-reproducibility.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="r-publishing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/merely-useful/merely-useful.github.io/edit/master/r-data-manipulation.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["r.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
